### ISSUE TITLE
Personal settings: Edit Private Website Settings has no effect

### ISSUE THREAD

**Issue by doftnet** [nextcloud/cms_pico#100]
Attempting to change a site from private to public or public to private currently appears to have no effect (Pico CMS v 1.0.2, NC 17.0.1)

## Process:
go to personal settings -> Pico CMS
Click lock icon to open the Edit Private Website Settings dialog
make changes
Click Save

## Expected results:
changed settings get applied

## Actual Results:
Dialog closes. Nothing changes. Database unaffected.
Javascript console shows "type=1&options%5Bgroup_access%5D=" or something similar, reflecting the values submitted, but nothing actually gets saved.

Snooping around in the Javascript, it appears that a large chunk of the script that previously handled the change is commented out so I suspect this is probably a work in progress and hopefully this will be functioning as intended in an upcoming release.  As a workaround, I can manually change the type field in the database directly but only because I'm also the DB admin. Other users obviously don't have that luxury and even I don't particularly like futzing with the DB directly if I can avoid it.

**Comment by PhrozenByte** [comment]
Fixed with v1.0.3, there got something mixed up in the release process. Will apply some precaution in the future. Thank you for your bug report! :+1:
