### ISSUE TITLE
cms for an NC specific (grouped) folder

### ISSUE THREAD

**Issue by DarkknightAK** [nextcloud/cms_pico#106]
Hi,

I use the README.md extension for grouped folders cause there the users can add the description of there projects into the specific folders OR for global folders like template folders the company related descriptions are stored in README.md.

my question is can cms_pico be the cms of the NC?

So there are 3 hierarchy items
1. NC files
    2. README.md (if installed)
        3. cms_pico

So NC contain the files, README.md contain the .md stuff and cms_pico will be the cms that link all together.

**Comment by PhrozenByte** [comment]
To be honest I don't really understand what you're trying to achieve, please elaborate further. Pico CMS for Nextcloud requires a rather strict directory structure to work.

**Comment by DarkknightAK** [comment]
Close for now as long as I don't have a clear idea.
