### ISSUE TITLE
How to turn off right margin justification

### ISSUE THREAD

**Issue by rollanders** [nextcloud/cms_pico#108]
After the last update all text is right margin justified. Maybe it was like that also before.  Can I turn that off? The reason is that it sometimes does not scale well in the telephone. 

NC17.0.2
PicoCMS 1.0.4

**Comment by PhrozenByte** [comment]
Can you provide some screenshot and elaborate further?

**Comment by rollanders** [comment]
Maybe you have worked a lot on this and I am a newcomer. I have not reacted previously to the justified text in PicoCMS when reading on the phone but it happened today. The words were unevenly spaced over lines and both right and left margins were straight. If some words are very long this can give a weird impact. I am not sure that the alternative of a very shragged right margin would be better. 

But this suppports my view  https://www.webdesignerdepot.com/2015/02/7-simple-rules-for-mobile-typography/
Here a "fake" bad example from my phone. 

![image](https://user-images.githubusercontent.com/36486009/72456511-16deb300-37c5-11ea-906b-aeae41551c71.png)
Below a picture from the referred text. 
![image](https://user-images.githubusercontent.com/36486009/72457241-72f60700-37c6-11ea-94bc-a0083bf3920d.png)

**Comment by PhrozenByte** [comment]
That's expected behaviour, the contents are justified. You should add soft breaks (`&shy;`) to long words to prevent this. If you really want to achieve left alignment, create a custom theme and remove the appropriate `text-align: justify` CSS rules.

**Comment by rollanders** [comment]
If expected behaviour I still think it is not optimal webbdesign. Mobile windows come in various sizes. I cannot add breaks everywhere.  Check out an read some newspapers in the phone and you will see they do not use justified pages, ie they use the first example shown above. 

I find text-align: justify; on line 372 in /var/www/nextcloud/apps/cms_pico/css/pico.scss  Is that the line I should edit?

**Comment by PhrozenByte** [comment]
> I find text-align: justify; on line 372 in /var/www/nextcloud/apps/cms_pico/css/pico.scss Is that the line I should edit?

No, it's in your theme, i.e. `/var/www/nextcloud/apps/cms_pico/appdata_public/themes/default/css/theme.css`. However, you must not edit this file but create a custom theme.
