### ISSUE TITLE
Error when activating in NC18.0.0 RC2

### ISSUE THREAD

**Issue by rollanders** [nextcloud/cms_pico#109]
Upgraded to NC18.0.0 RC2. Initially it seemed as PicoCMS woked but next time I got this error
I have all the newest apps. I use the app externalsites to access my PicoCMS 

[index] Error: Exception: Call to undefined method ParsedownExtra::textElements() at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\CMSPico\Controller\PicoController {}, "getPage")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\CMSPico\\C ... r", "getPage", OC\AppFramework\ ... {}, {page: "",site:  ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({page: "",site:  ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {page: "",site:  ... "})
4. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/cms_pico/pico/gemenskap")
5. /var/www/nextcloud/index.php line 38
   OC::handleRequest()

GET /index.php/apps/cms_pico/pico/gemenskap
from 192.168.1.1 by NCadmin at 2020-01-15T17:53:54+01:00

**Comment by PhrozenByte** [comment]
Please always use GitHubs search engine before reporting issues. See #97
