### ISSUE TITLE
When pico cms is loaded on nextcloud 18 admin cant see any users

### ISSUE THREAD

**Issue by small1** [nextcloud/cms_pico#110]
Upgrade from 17.0.2 to 18.0 have pico cms enabled and as an admin go to the user admin interface. The list of users is empty and an error will occur.

'''
{"reqId":"xN7rL99M10MbbsAHHX5r","level":3,"time":"2020-01-26T18:27:29+00:00","remoteAddr":"92.35.16.173","user":"johan","app":"no app in context","method":"GET","url":"/ocs/v2.php/cloud/users/details?offset=0&limit=25&search=","message":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\CMSPico\\AppInfo\\Application::OCA\\CMSPico\\AppInfo\\{closure}() must be an instance of Symfony\\Component\\EventDispatcher\\Event, instance of OCP\\EventDispatcher\\GenericEvent given, called in /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 247","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"getUsersDetails"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","getUsersDetails",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.provisioning_api.Users.getUsersDetails"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"ocs.provisioning_api.Users.getUsersDetails"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.provisioning_api.Users.getUsersDetails"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users/details"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\CMSPico\\AppInfo\\Application::OCA\\CMSPico\\AppInfo\\{closure}() must be an instance of Symfony\\Component\\EventDispatcher\\Event, instance of OCP\\EventDispatcher\\GenericEvent given, called in /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 247","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":247,"function":"OCA\\CMSPico\\AppInfo\\{closure}","class":"OCA\\CMSPico\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":80,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":63,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/files_external/lib/Service/BackendService.php","line":117,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/files_external/lib/Service/BackendService.php","line":124,"function":"callForRegistrations","class":"OCA\\Files_External\\Service\\BackendService","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/files_external/lib/Service/BackendService.php","line":229,"function":"loadBackendProviders","class":"OCA\\Files_External\\Service\\BackendService","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/files_external/lib/Service/StoragesService.php","line":302,"function":"getBackend","class":"OCA\\Files_External\\Service\\BackendService","type":"->","args":["local"]},{"file":"/var/www/nextcloud/apps/files_external/lib/Service/StoragesService.php","line":102,"function":"createStorage","class":"OCA\\Files_External\\Service\\StoragesService","type":"->","args":["/Uploads","local","null::null",{"datadir":"/var/uploads"},{"encrypt":true,"previews":true,"enable_sharing":true,"filesystem_check_changes":1,"encoding_compatibility":false,"readonly":false},["johan"],[],150]},{"function":"getStorageConfigFromDBMount","class":"OCA\\Files_External\\Service\\StoragesService","type":"->","args":[{"mount_id":"1","mount_point":"/Uploads","storage_backend":"local","auth_backend":"null::null","priority":150,"type":1,"applicable":[{"type":3,"value":"johan","mount_id":"1"}],"config":{"datadir":"/var/uploads"},"options":{"encrypt":true,"previews":true,"enable_sharing":true,"filesystem_check_changes":1,"encoding_compatibility":false,"readonly":false}}]},{"file":"/var/www/nextcloud/apps/files_external/lib/Service/UserGlobalStoragesService.php","line":189,"function":"array_map","args":[[{"__class__":"OCA\\Files_External\\Service\\UserGlobalStoragesService"},"getStorageConfigFromDBMount"],[{"mount_id":"1","mount_point":"/Uploads","storage_backend":"local","auth_backend":"null::null","priority":150,"type":1,"applicable":[{"type":3,"value":"johan","mount_id":"1"}],"config":{"datadir":"/var/uploads"},"options":{"encrypt":true,"previews":true,"enable_sharing":true,"filesystem_check_changes":1,"encoding_compatibility":false,"readonly":false}}]]},{"file":"/var/www/nextcloud/apps/files_external/lib/Config/ConfigAdapter.php","line":128,"function":"getAllStoragesForUser","class":"OCA\\Files_External\\Service\\UserGlobalStoragesService","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":104,"function":"getMountsForUser","class":"OCA\\Files_External\\Config\\ConfigAdapter","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Storage\\StorageFactory"}]},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":448,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Mount\\Manager"}]},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["johan"]},{"file":"/var/www/nextcloud/lib/private/legacy/util.php","line":310,"function":"init","class":"OC\\Files\\Filesystem","type":"::","args":["johan","/johan/files"]},{"file":"/var/www/nextcloud/apps/provisioning_api/lib/Controller/AUserData.php","line":192,"function":"setupFS","class":"OC_Util","type":"::","args":["johan"]},{"file":"/var/www/nextcloud/apps/provisioning_api/lib/Controller/AUserData.php","line":140,"function":"fillStorageInfo","class":"OCA\\Provisioning_API\\Controller\\AUserData","type":"->","args":["johan"]},{"file":"/var/www/nextcloud/apps/provisioning_api/lib/Controller/UsersController.php","line":195,"function":"getUserData","class":"OCA\\Provisioning_API\\Controller\\AUserData","type":"->","args":["johan"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getUsersDetails","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["",25,0]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"getUsersDetails"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"getUsersDetails"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","getUsersDetails",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.provisioning_api.Users.getUsersDetails"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"ocs.provisioning_api.Users.getUsersDetails"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.provisioning_api.Users.getUsersDetails"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users/details"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/cms_pico/lib/AppInfo/Application.php","Line":64},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","version":"18.0.0.10"}
'''

**Comment by PhrozenByte** [comment]
Weird... Unless they changed the class tree, `OCP\EventDispatcher\GenericEvent` should be an instance of `Symfony\Component\EventDispatcher\Event` :confused: Will look into this, but might take some days.

**Comment by small1** [comment]
I will check more in my logs. But it might also be external storage support that is the culprit for both my bugs or a combination of them.

**Comment by PhrozenByte** [comment]
Ok, wow, this is bad. Looks like Nextcloud 18 indeed changed the class hierarchy. Changing the public API in a incompatible manner without a transition time and/or notice is an absolute No-Go :unamused: This is especially bad because this can't be solved without an explicit version switch.

Anyway, since we don't rely on this parameter we can remove it. This doesn't really solve the underlying issue (NC changing public API), but it works...

**Comment by dcrobertson01** [comment]
Hi - same issue here. The fix (https://github.com/nextcloud/cms_pico/commit/3a7bce35c32a344226b600f74519cd8ccb5db2b3) does not work for me.

**Comment by dcrobertson01** [comment]
Correction - the fix (https://github.com/nextcloud/cms_pico/commit/3a7bce35c32a344226b600f74519cd8ccb5db2b3) **does** work for me. Did not read the whole thing :-)
