### ISSUE TITLE
collabora online get deactivated when activating cms pico on nc18

### ISSUE THREAD

**Issue by small1** [nextcloud/cms_pico#111]
If i activate pico cms on nextcloud 18 collabroa online is deactivated.

**Comment by PhrozenByte** [comment]
There's nothing intentional happening here from Pico CMS for Nextcloud's side, so you should ask the developers of NC's Collabora Online app what the problem might be; an app shouldn't disable itself unintentionally.

**Comment by small1** [comment]
I have deducted its either pico cms or external folder. I did file a bug against external folders as well. And it is related to #110  it seems. As both happens at the same time.

**Comment by parajbs** [comment]
Not only Collabora Online app has problems, external storage also crashes!
