### ISSUE TITLE
End user documentation: where to put a *.md file and how to access it.

### ISSUE THREAD

**Issue by markuskramerIgitt** [nextcloud/cms_pico#113]
I just installed picocms 1.04 in a NexCloud 17 instance I do not administer.

I do not find in the user documentation:
- Where to put a first *.md file?
- How to access it?

**Comment by markuskramerIgitt** [comment]
Answers to both questions:
- Go to the Nextcloud Settings
- In the personal settings, select Pico CMS
- Create a website with the sample_template.
- Access your markdown files via the folder icon  with "go to website directory" mouseover.
- Access the sample template website via the world icon  with "go to website" mouseover.

**Comment by PhrozenByte** [comment]
See Pico's `README.md` resp. app store description:

> You want to learn more about Pico CMS for Nextcloud? Easy! Just download and enable the app from Nextcloud's App Store and navigate to Nextcloud's settings page. As an admin you'll find two "Pico CMS" sections in your Nextcloud settings - one below "Personal", another below "Administration". The latter allows you to add custom themes, plugins and templates to Pico, as well as tweaking some advanced settings. The "Pico CMS" section below "Personal" exists for all Nextcloud users and allows one to create personal websites. Simply create your first personal website and choose "sample_pico" as website template. Pico's sample contents will explain all you need to know… :wave:

**Comment by markuskramerIgitt** [comment]
Maybe copy that to the wiki?
I first read the docs, then the app store description.

**Comment by PhrozenByte** [comment]
The wiki is no longer used (and all links have been removed from the app's `info.xml`) since including all necessary details in the app is the better approach IMO. For "pre-usage" info like the mentioned I honestly don't see an advantage in having a *third* copy of the same contents (app store resp. `info.xml` + `README.md` + then wiki) at a place that's nowhere mentioned?

**Comment by markuskramerIgitt** [comment]
Thank you, I agree  and close this here.
