### ISSUE TITLE
File paths ?

### ISSUE THREAD

**Issue by dcrobertson01** [nextcloud/cms_pico#115]
Hi - I have had bit of a look around, but have not found a solution to this. Also, have my 4 yo to look after today, so will just ask a quick question.

I am working on a theme for use with Pico in Nextcloud. I am using PHP's inbuilt server to work on it. On this server, I get urls with a question mark in them - like https://server/?docs
When I install this on Nextcloud for cms_pic, I get urls without a question mark - eg https:/server/index.php/apps/cms_pico/pico/learn2/docs. 

My theme is adding the path (?docs) to the base_url, and it is not working. Removing the qusetion mark manually does work.

Is this difference something you have done, or is it a Pico setting? I do not see it in the Pico docs.

Unfortunately I have to disappear  now or would look into it some more. 

This is the repository but I will need to modify it to include templates etc. But feel free to have a look.

**Comment by PhrozenByte** [comment]
You should always use Pico's `link` Twig filter for creating page links (e.g. `{{ "sub/page"|link }}`), the filter will take care of URL rewriting. See http://picocms.org/docs/#twig-filters-and-functions

**Comment by dcrobertson01** [comment]
Facepalm. Yeah - a function to filter links in a content management system. Who would have thought it?

I think that should do the trick. Will test it out later on.

**Comment by dcrobertson01** [comment]
Okay - I have changed the address of the repository - but I see the url is not posted here anyway :-) Don't know what happened there. 
New place: https://github.com/dcrobertson01/picocms-theme-learn2
Only posting the link because I mentioned it earlier. The theme works, but there is a lot more to be done and I won't get back to it for a bit.
But feel free to try it out if you so desire :-)
