### ISSUE TITLE
possible improvement for short urls webserver config

### ISSUE THREAD

**Issue by AvverbioPronome** [nextcloud/cms_pico#117]
I wanted to configure my instance to use short urls an I found this in the suggested config:

```pre
proxy_pass http://nc.myowndomain.example.com/index.php/apps/cms_pico/pico_proxy/;
```

this will not work for me. My install is behind a reverse proxy and there is nothing listening on port 80 on the public interface. 

I had success replacing the fqdn with a simple `localhost`.

**Comment by PhrozenByte** [comment]
This highly depends on your webserver config, on most configs a simple `http://localhost/` won't work.

**Comment by AvverbioPronome** [comment]
You're right, it would not work for webservers with virtualhosts (mine is dockerized, and virtualhosts are on the reverse proxy, so no problem).

But then I read nginx [documentation](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) and I realized I could pass the original `Host` header by including 
```pre
proxy_set_header Host       $http_host;
```

**Comment by AvverbioPronome** [comment]
Should this go in the documentation, at least?

**Comment by PhrozenByte** [comment]
Since this is an absolute edge case and won't affect 99% of all users, it likely rather causes confusion. Since we don't ever delete any issues one can still find this issue resp. solution.
