### ISSUE TITLE
NC 18: File not found at path: efa.vor.at/vor

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/cms_pico#119]
trying to download and enable I get this error

**Comment by PhrozenByte** [comment]
Without a lot more information about what you're trying to do, what exact errors you're receiving, the contents of your logfiles, etc. we can't really help you...

**Comment by ferdiga** [comment]
thanks for looking into this
apparently  this causes the issue
"efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"


{"reqId":"FfWYkv2jonSlp2pZ631N","level":3,"time":"2020-03-26T00:02:48+00:00","remoteAddr":"111.235.143.43","user":"myuser","app":"settings","method":"POST","url":"/nextcloud/index.php/settings/apps/enable","message":{"Exception":"League\\Flysystem\\FileNotFoundException","Message":"File not found at path: efa.vor.at/vor","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Storage/Flysystem.php","line":82,"function":"buildPath","class":"OCA\\Files_external_gdrive\\Storage\\Flysystem","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Common.php","line":137,"function":"file_exists","class":"OC\\Files\\Storage\\Flysystem","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Common.php","line":171,"function":"isReadable","class":"OC\\Files\\Storage\\Common","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Common.php","line":700,"function":"getPermissions","class":"OC\\Files\\Storage\\Common","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":582,"function":"getMetaData","class":"OC\\Files\\Storage\\Common","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php","line":145,"function":"getMetaData","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":582,"function":"getMetaData","class":"OC\\Files\\Storage\\Wrapper\\PermissionsMask","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php","line":443,"function":"getMetaData","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":582,"function":"getMetaData","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":113,"function":"getMetaData","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":151,"function":"getData","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":439,"function":"scanFile","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf",3,36196186,null,true]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":407,"function":"handleChildren","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["",false,3,36196186,true,-1]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":339,"function":"scanChildren","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["",false,3,36196186,true]},{"file":"/var/www/nextcloud/lib/private/Files/Utils/Scanner.php","line":261,"function":"scan","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["",false,3]},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Files/StorageFolder.php","line":176,"function":"scan","class":"OC\\Files\\Utils\\Scanner","type":"->","args":["/",false]},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Service/FileService.php","line":186,"function":"sync","class":"OCA\\CMSPico\\Files\\StorageFolder","type":"->","args":[false]},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Migration/AppDataRepairStep.php","line":143,"function":"syncAppDataFolder","class":"OCA\\CMSPico\\Service\\FileService","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Migration/AppDataRepairStep.php","line":123,"function":"syncAppDataFolder","class":"OCA\\CMSPico\\Migration\\AppDataRepairStep","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Repair.php","line":104,"function":"run","class":"OCA\\CMSPico\\Migration\\AppDataRepairStep","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"/var/www/nextcloud/lib/private/legacy/app.php","line":981,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Installer.php","line":169,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["cms_pico",{"step":"OCA\\CMSPico\\Migration\\AppDataRepairStep"}]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":443,"function":"installApp","class":"OC\\Installer","type":"->","args":["cms_pico"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["cms_pico"],[]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/files_external_gdrive/lib/Storage/Flysystem.php","Line":86,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.87 Chrome/80.0.3987.87 Safari/537.36","version":"18.0.3.0"}

**Comment by PhrozenByte** [comment]
Looks like some side effect, this issue isn't caused by Pico CMS for Nextcloud, it just triggers the issue. The filesystem scanner is trying to scan some `efa.vor.at/vor/FILELOAD?Filename=aut_5241830E2F.pdf` file, even though this doesn't even look like a local path. Try disabling all your custom apps **one after another** and try whether activating Pico CMS for Nextcloud works at every step - this way you'll identify the app that's causing this issue.

**Comment by ferdiga** [comment]
the problem was "External storage support for Google Drive"
the file is in the database and in google drive 
apparently it's possible to leave the app enabled even though it's not supported. 
after disabling enabling  was possible

thanks !!
