### ISSUE TITLE
NC18: wrong path for data

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/cms_pico#120]
the datadirectory = /nextcloud_data
the app looks up in the base directory /nextcloud instead of the datadirectory

/nextcloud/index.php/apps/cms_pico/pico/test1/assets-5e7dce72ae2fc/image.png

furthermore the name .../assets-5e7dce72ae2fc/... should probably only be .../asset/.... as assets-5e7dce72ae2fc does not exist in the data directory neither.

**Comment by PhrozenByte** [comment]
>  the app looks up in the base directory /nextcloud instead of the datadirectory

Where does it look up what? What issue are you facing?

> furthermore the name .../assets-5e7dce72ae2fc/... should probably only be .../asset/

No. URL paths aren't equal to filesystem paths.

**Comment by ferdiga** [comment]
lookup of image.png - 3rd line above
the test1 directory is in
/nextcloud**_data**/index.php/apps/cms_pico/pico/test1/assets-5e7dce72ae2fc/image.png

**Comment by ferdiga** [comment]
{"Exception":"Error","Message":"Call to undefined method ParsedownExtra::textElements()","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/cms_pico/vendor/picocms/pico/lib/Pico.php","line":1662,"function":"text","class":"ParsedownExtra","type":"->","args":["\n## Welcome to Pico\n\n![Nextcloud Logo](/nextcloud/index.php/apps/cms_pico/pico/test1/assets-5e7dce72ae2fc/image.png)\n\nCongratulations

**Comment by ferdiga** [comment]
Ah interesting - here the link above points to the github URL

> https://github.com/nextcloud/index.php/apps/cms_pico/pico/test1/assets-5e7dce72ae2fc/image.png

**Comment by PhrozenByte** [comment]
So? As I said, URL paths != filesystem paths. The URL looks just fine.

Regarding the exception: See #97
