### ISSUE TITLE
Serving arbitrary HTML pages

### ISSUE THREAD

**Issue by ifuchs** [nextcloud/cms_pico#122]
I am looking for a way to serve webpages that have been captured by the Scrapbook Firefox plugin. The plugin captures everything needed and the local files can be viewed in the browser. Is there a away to put these files in Nextcloud and use Pico CMS to serve them? I know I can add HTML to a markdown doc but this would involve having a folder that contains the html files, CSS, images, etc. Of course I could just run another apache server but I wondered if this could be done with pico from NC.

**Comment by PhrozenByte** [comment]
Unfortunately not. Pico CMS for Nextcloud expects Markdown files as input and displays them inside a Twig template to create a "complete" web page. Furthermore Pico CMS for Nextcloud strips any active source code (like JavaScript and HTML forms) from content files for security reasons - what will likely break your captures.

Anyway, a tip from a Nextcloud user: A remote storage mapping a local folder on your webserver to your Nextcloud might be a solution for you. It's just important to keep in mind that you might create severe security issues by doing so, thus you should limit this to yourself.

**Comment by ifuchs** [comment]
Could I map all of /var/www/html (files and folders) on web server to NC. What would that buy me? Ability to maintain web server files via NC? Anything else?

**Comment by PhrozenByte** [comment]
I wouldn't map `/var/www/html`, but some sub folder in which you wanna store and access your website captures from. Please keep in mind that this is a off-topic suggestion from me as some random Nextcloud user, it has absolutely nothing to do with Pico CMS for Nextcloud.

**Comment by ifuchs** [comment]
Thanks! It’s worth testing.

**Comment by ifuchs** [comment]
I added the /var/www/html directory of my (other) web server as external storage and it works (sort of). I can access all of the files but there are some strange behaviors. In the NC web interface, files with an .html suffix open as editable files. However, if I open the same file in the IOS app, it tries to render the html which doesn't always work well. Stranger, when I open a file with a .py suffix, the web interface spins its wheel and the ios app renders the file but it is not editable. Obviously I am trying to do some things for which NC was not intended. I am also not sure how to make use of picocms in this context. What I would like to be able to do is view multimedia files (seems to work) and edit files such as those with .php, .py, and .html suffixes.
