### ISSUE TITLE
Rename website?

### ISSUE THREAD

**Issue by killerbees19** [nextcloud/cms_pico#123]
I know, it's possible by changing the field `name` at `oc_cms_pico_websites` table.

But it would be nice if there's an option for regular users to rename sites via web… 🙂

(_Maybe it's already there and I've missed it?_)

**Comment by PhrozenByte** [comment]
You can simply delete and re-create the website, Pico CMS for Nextcloud never touches any of your files.

Anyway, this is a super basic feature, that's for sure. It's already in the TODO list for Pico CMS for Nextcloud v1.1 (see #99). Now we also have a Issue for that :smile:

**Comment by killerbees19** [comment]
> You can simply delete and re-create the website, Pico CMS for Nextcloud never touches any of your files.

Thanks, nice workaround. :smiley: 

> It's already in the TODO list for Pico CMS for Nextcloud v1.1 (see #99).

Great :+1:
