### ISSUE TITLE
External images fail to load due to CSP

### ISSUE THREAD

**Issue by kc853** [nextcloud/cms_pico#126]
Running cms_pico 1.0.5 on dockerized NC18.0.4. 

After playing around for a day I realized, that external images can't be loaded due to CSP.

`Refused to load the image 'https://x.png' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".`

Is there a way to fix that without touching the container?

Regards

**Comment by PhrozenByte** [comment]
This is intended behaviour. You can't include external contents due to security reasons. Also see https://github.com/nextcloud/cms_pico/pull/99#issuecomment-617311003

**Comment by kc853** [comment]
OK. Understand that. Please point that out at the cms-pico page at Nextcloud apps.
[https://apps.nextcloud.com/apps/cms_pico](url)
