### ISSUE TITLE
Cannot activate CMS_PICO on NC 18 OCP\Files\NotPermittedException:

### ISSUE THREAD

**Issue by mamiapatrick** [nextcloud/cms_pico#127]
hello 
i'm trying to install cms pico on nextcloud 18 with backend database on MariaDB. When i try to activate the module i see that message on the logging message :

 `

settings | OCP\Files\NotPermittedException: /var/www/html/custom_apps/cms_pico/lib/Service/FileService.php - line 186: OCA\CMSPico\Files\StorageFolder->sync(false)/var/www/html/custom_apps/cms_pico/lib/Migration/AppDataRepairStep.php - line 143: OCA\CMSPico\Service\FileService->syncAppDataFolder()/var/www/html/custom_apps/cms_pico/lib/Migration/AppDataRepairStep.php - line 123: OCA\CMSPico\Migration\AppDataRepairStep->syncAppDataFolder()/var/www/html/lib/private/Repair.php - line 104: OCA\CMSPico\Migration\AppDataRepairStep->run(OC\Repair {})/var/www/html/lib/private/legacy/app.php - line 981: OC\Repair->run()/var/www/html/lib/private/Installer.php - line 169: OC_App::executeRepairSteps("cms_pico", { step: "OCA ... "})/var/www/html/apps/settings/lib/Controller/AppSettingsController.php - line 443: OC\Installer->installApp("cms_pico")/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 170: OCA\Settings\Controller\AppSettingsController->enableApps([ "cms_pico"], [])/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")/var/www/html/lib/private/AppFramework/App.php - line 125: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})/var/www/html/lib/private/Route/Router.php - line 299: call_user_func(OC\AppFramew ... {}, { _route: "s ... "})/var/www/html/lib/base.php - line 1008: OC\Route\Router->match("/settings/apps/enable")/var/www/html/index.php - line 38: OC::handleRequest()
-- | --

`

**Comment by PhrozenByte** [comment]
Deactivate your files_external provider apps, this is likely caused by one of them.

**Comment by mamiapatrick** [comment]
Hello @PhrozenByte as far as i know i don't have any files_external provider apps...

**Comment by PhrozenByte** [comment]
Check that your webserver resp. PHP has write access to all files and directories in your `data` directory.

**Comment by amsaravi** [comment]
i have same problem with NC18
[PHP] Error: require_once(): Failed opening required '/var/www/html/apps/cms_pico/appdata_public/plugins/bwBO2gbY5s//PicoDeprecated/PicoDeprecated.php' (include_path='/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Translation:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Util:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Nls:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Exception:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Date:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Filter:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Stream:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Socket_Client:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Wrapper:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Support:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Crypt_Blowfish:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Secret:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Flowed:/ at /var/www/html/apps/cms_pico/lib/Service/PicoService.php#215

GET /index.php/apps/cms_pico/pico/my_first_test_id
from 192.168.1.124 by amsaravi at 2020-05-05T08:47:34+00:00

**Comment by amsaravi** [comment]
i have same problem with NC18
[PHP] Error: require_once(): Failed opening required '/var/www/html/apps/cms_pico/appdata_public/plugins/bwBO2gbY5s//PicoDeprecated/PicoDeprecated.php' (include_path='/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Translation:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Util:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Nls:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Exception:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Date:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Filter:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Stream:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Socket_Client:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Wrapper:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Support:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Crypt_Blowfish:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Secret:/var/www/html/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Flowed:/ at /var/www/html/apps/cms_pico/lib/Service/PicoService.php#215

GET /index.php/apps/cms_pico/pico/my_first_test_id
from 192.168.1.124 by amsaravi at 2020-05-05T08:47:34+00:00

**Comment by amsaravi** [comment]
I tried both app store and manual installation and both installation completed successfully but what can i see is a blank page after defining a site

**Comment by PhrozenByte** [comment]
Looks like you somehow got yourself into a partial installation of the app. Try running `occ maintenance:repair` and make sure that your webserver resp. PHP has full read & write permissions on all files and dirs in your `data` directory.
