### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Ramdane34** [nextcloud/cms_pico#130]
Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

**Comment by PhrozenByte** [comment]
Please check your Nextcloud and server logs

**Comment by Ramdane34** [comment]
hello and thank you for answering
here is the log:

Exception: Call to undefined method ParsedownExtra::textElements()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 125:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\CMSPico\ ... {}, "getPage")

    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\CMSPic ... r", "getPage", OC\AppFramew ... {}, { page: "",s ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ page: "",s ... "})

    /var/www/nextcloud/lib/private/Route/Router.php - line 299:

    call_user_func(OC\AppFramew ... {}, { page: "",s ... "})

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/cms_pico/pico/blog2")

    /var/www/nextcloud/index.php - line 38:

    OC::handleRequest()

**Comment by Ramdane34** [comment]
`

  | Exception: Call to undefined method ParsedownExtra::textElements()/var/www/nextcloud/lib/private/AppFramework/App.php - line 125: OC\AppFramework\Http\Dispatcher->dispatch(OCA\CMSPico\ ... {}, "getPage")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\CMSPic ... r", "getPage", OC\AppFramew ... {}, { page: "",s ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ page: "",s ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(OC\AppFramew ... {}, { page: "",s ... "})/var/www/nextcloud/lib/base.php - line 1008: OC\Route\Router->match("/apps/cms_pico/pico/blog2")/var/www/nextcloud/index.php - line 38: OC::handleRequest()Causé parError: Call to undefined method ParsedownExtra::textElements()/var/www/nextcloud/apps/cms_pico/vendor/picocms/pico/lib/Pico.php - line 1662: ParsedownExtra->text("\n# Error 4 ... n")/var/www/nextcloud/apps/cms_pico/lib/Pico.php - line 211: Pico->parseFileContent("\n# Error 4 ... n", false)/var/www/nextcloud/apps/cms_pico/vendor/picocms/pico/lib/Pico.php - line 487: OCA\CMSPico\Pico->parseFileContent("\n# Error 4 ... n")/var/www/nextcloud/apps/cms_pico/lib/Pico.php - line 104: Pico->run()/var/www/nextcloud/apps/cms_pico/lib/Service/PicoService.php - line 147: OCA\CMSPico\Pico->run()/var/www/nextcloud/apps/cms_pico/lib/Service/WebsitesService.php - line 282: OCA\CMSPico\Service\PicoService->getPage(OCA\CMSPico\Model\Website {})/var/www/nextcloud/apps/cms_pico/lib/Controller/PicoController.php - line 108: OCA\CMSPico\Service\WebsitesService->getPage("blog2", "", "admin", false)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170: OCA\CMSPico\Controller\PicoController->getPage("blog2", "", false)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\CMSPico\ ... {}, "getPage")/var/www/nextcloud/lib/private/AppFramework/App.php - line 125: OC\AppFramework\Http\Dispatcher->dispatch(OCA\CMSPico\ ... {}, "getPage")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\CMSPic ... r", "getPage", OC\AppFramew ... {}, { page: "",s ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ page: "",s ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(OC\AppFramew ... {}, { page: "",s ... "})/var/www/nextcloud/lib/base.php - line 1008: OC\Route\Router->match("/apps/cms_pico/pico/blog2")/var/www/nextcloud/index.php - line 38: OC::handleRequest()
-- | --


`

**Comment by Ramdane34** [comment]
[index] Error: Exception: Call to undefined method ParsedownExtra::textElements() at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\CMSPico\Controller\PicoController {}, "getPage")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\CMSPico\\C ... r", "getPage", OC\AppFramework\ ... {}, {page: "",site:  ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({page: "",site:  ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {page: "",site:  ... "})
4. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/cms_pico/pico/blog2")
5. /var/www/nextcloud/index.php line 38
   OC::handleRequest()

GET /index.php/apps/cms_pico/pico/blog2
from 192.168.0.254 by admin at 2020-05-26T05:31:08+00:00

**Comment by PhrozenByte** [comment]
Duplicate of #97

**Comment by Ramdane34** [comment]
thanks problem solved
