### ISSUE TITLE
Group folders

### ISSUE THREAD

**Issue by nikkilocke** [nextcloud/cms_pico#134]
We have a large Nextcloud, and we would like to use Pico with it.

However, none of our users have any personal quota (so they cannot store files in their personal spaces) - we use group folders to allow entire groups a common space.

Is it possible to make pico work with group folders instead of personal ones?

**Comment by killerbees19** [comment]
> Is it possible to make pico work with group folders instead of personal ones?

Seems like it's possible. I've just created a new CMS with example data stored at a group folder without any issues. I've not tested editing files or uploading assets with another user, but I don't think this should be a problem.

**Comment by nikkilocke** [comment]
That's great news! 
But how did you do it?
In my Nextcloud, in settings/pico cms, there doesn't seem to be an option to put the site in a particular folder.

**Comment by nikkilocke** [comment]
Sorry, stupid - I didn't realise the path was editable.
