### ISSUE TITLE
Embed PDF file in site

### ISSUE THREAD

**Issue by JoshuaPettus** [nextcloud/cms_pico#135]
Is there anyway to embed a pdf document into a site?  It seems the embed HTML tag is not recognized by picocms

```
<embed src="linktopdf" width="200px" height="400px" /> 
```
I've even tried both using the relative link /to/pdf/file.pdf  and straight up sharing the pdf as a link in the nextcloud files app.  I get nothing.  Though <a href="linktopdf">pdf</a> works just fine.

I can't seem to find any sort of plugins to help me out either.

**Comment by JoshuaPettus** [comment]
This is for sheet music I'd like to embed in the page.

Actually even better would be for me to use the musescore.com embed iframe feature, but I saw an old thread here that that was not supported and would be something that you would look into post 1.0 release.  Is there any hope of getting that to work currently?

**Comment by PhrozenByte** [comment]
You can't embed files with Pico CMS for Nextcloud due to security reasons: PDF files resp. the `<embed>` HTML tag is considered active content and would allow arbitrary users to perform XSS attack against your Nextcloud otherwise. Thus the tag is stripped. This is intended behaviour. #83 is a potential solution.

**Comment by JoshuaPettus** [comment]
This is what I don't understand.  If the file is outside of the website, and is using a link generated by the nextcloud files app,  doesn't that avoid the whole situation?  If there is a security risk from a nextcloud generated link, then nextcloud's got problems...
Or maybe I'm not understanding what exactly an XSS attack is.

FTR I already have nginx setup for the website to be accessed from a different subdomain through proxy passing. (As per the suggestion on #83).  Works great.

Also is iframes ignored for the same reason?

**Comment by PhrozenByte** [comment]
Obviously you can prevent XSS issues by circumventing the multiple possible attack vendors, however, the `<embed>` HTML tag simply can't prevent users from not creating XSS issues. Thus it's stripped. Same for iframes.

**Comment by JoshuaPettus** [comment]
That's very unfortunate,  but thank-you for answering!
