### ISSUE TITLE
Nextcloud log file full of errors: "Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/cms_pico/vendor/erusev/parsedown-extra/ParsedownExtra.php#338"

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/cms_pico#136]
Many many instances of this error in my Nexcloud log:

```
Trying  to access array offset on value of type null at  /var/www/html/nextcloud/apps/cms_pico/vendor/erusev/parsedown-extra/ParsedownExtra.php#338
```

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser: Not applicable
 - Version: Not applicable

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - HTTP server: lighttpd 1.4.55
 - Database: Postgresql 12.4
 - PHP version: 7.4.3
 - Nextcloud version: 19.0.2
 - Bookmarks app version: 3.3.4
 - Activated Nextcloud Apps:
```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - bookmarks: 3.3.4
  - bruteforcesettings: 2.0.0
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - cms_pico: 1.0.8
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_markdown: 2.3.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 2.0.3
  - groupfolders: 7.0.0
  - joplin: 0.0.25
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.3
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
 - Nextcloud configuration:
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nephele.thumbs.place",
            "nephele.lan",
            "192.168.0.14"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "19.0.2.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "logtimezone": "Australia\/Hobart",
        "loglevel": "2",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded-for-headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "joplin"
        ],
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/nephele.thumbs.place",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
```

**Comment by bernd-wechner** [comment]
There's a currently a site live at:

https://nephele.thumbs.place/index.php/apps/cms_pico/pico/pico_test/theme

which produces this error 9 times when it's loaded. Tested in isolation, emptied my Nextcloud log, loaded that page and watched. First test I did to try and trace it and voila.

**Comment by bernd-wechner** [comment]
Beyond comprehension. But this is exactly what I did. I traced the theme source to:

`/var/www/html/nextcloud/apps/cms_pico/appdata_public/themes/FRelq0qGNp/default/index.twig`

and so I opened that in an editor. Then, given the clues above told me these errors were only produced loading files in the `sub` folder I reloaded that one and saw the 9 errors unfold. Good. So then:

- I commented out the header in the file above and reloaded. The errors disappeared.
- I then halved the comment if you will (search by bisection), so I had only the site title and the navigation blocks commented. Reloaded, and no errors.
- I halved it again, and had only site navigation commented. Reloaded, no errors. 
- I uncommented that again and reloaded. Still no errors.

WTF?

So in my editor (Atom), I held down CTRL-Z and watched my edit history unfold before my eyes and revert this file to its orifginal, unedited form. Then reloaded the page. No errors.

They have gone for now and I can't reproduce them. Though they reliably appeared above when loading pages in the `sub` folder.

Unable to reproduce it, I doubt we can diagnose it. If I see it reappear I will be back.

**Comment by bernd-wechner** [comment]
Scratch that. Human error methinks. I found one cause. The horizontal rule `---` produces this error three times. The remaining six have yet to nail.

**Comment by bernd-wechner** [comment]
And I've nailed them all. Phew, that was laborious. Another three of those errors are produced by:

```
* Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
  - Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
  - Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
```

Specifically the lines starting with `-`

and the final 3 are produced by the broken table in htat sample file:

````
Lorem ipsum | Duis autem vel eum | Ut wisi enim ad minim veniam
----------- | ------------------ | ----------------------------
```

Broken because it doesn't even render without a thrid row (for the data) a la:

````
Lorem ipsum | Duis autem vel eum | Ut wisi enim ad minim veniam
----------- | ------------------ | ----------------------------
Lorem ipsum | Duis autem vel eum | Ut wisi enim ad minim veniam
```
But again, it's the leading `-` that produces the errors, if I use the complete syntax:

```
| Lorem ipsum | Duis autem vel eum | Ut wisi enim ad minim veniam |
| ----------- | ------------------ | ---------------------------- |
| Lorem ipsum | Duis autem vel eum | Ut wisi enim ad minim veniam |
```

There are now errors.  So all 9 of thes eerros traced to one page, and the use of:

1. A horizontal rule `---` but `***` works
2. A pair of list items prefixed with `-` but `*` works
3. A table with a header ending row starting with `-` but `| -` works.

There is something broken in this markdown processor currently.

**Comment by PhrozenByte** [comment]
With Parsedown we unfortunately face a lot of problems... This is one of the rather minor ones :unamused: 

Anyway, you might wanna give v1.0.9 a try, it uses Pico v2.1.4 which should now silence these errors. They are rather trivial and can safely be ignored.

**Comment by bernd-wechner** [comment]
Thanks for the update. 

Yes, these were inconsequential errors I admit but noise in my log file (Boy Who Cried Wolf syndrome) unwelcome as there's a lot of noise in there that I'm tracing,diagnosing and reporting, the next one of which is a Pico one as well (I'll share below).

Can you clarify (for a learning guy) what you meant by:  "give v1.0.9 a try, it uses Pico v2.1.4" . I did just update in the NextCloud Web UI the PicoCMS app to 1.0.9, got that, but what is Pico v2.1.4. At a guess, 1.0.9 is ht eversion of the Nexcloud cms_pico app, and 2.1.4 is the version of the PicoCMS that it's using?

From which I might conclude this was a PciCM issue (not the Nextcloud App but the CMS itself).

This morning the log file is full of:

```
Declaration of OCA\CMSPico\Http\PicoAssetResponse::cacheFor(int $cacheSeconds): OCA\CMSPico\Http\PicoAssetResponse should be compatible with OCP\AppFramework\Http\Response::cacheFor(int $cacheSeconds, bool $public = false) at /var/www/html/nextcloud/apps/cms_pico/lib/Http/PicoAssetResponse.php#104
```

Which is reminiscent of another issue I filed: https://github.com/nextcloud/bookmarks/issues/1187

and so I wonder if the conclusion is the same, and it relates a mix of PHP module versions (Nexcloud has a one version and the app carries its own local version and there's a namespace mixup in which on version' function is being compared with another version's interface spec.  In this case we can see the cacheFor interface demands a bool $public which the implementation doesn't implement. Very suggestive of a namespace/version mixup between the function declaration and the interface declaration.

**Comment by bernd-wechner** [comment]
But I want to report that after upgrading 1.0.9 yes the originally reported errors relating to those lines starting with `-` is gone. I can load the packaged theme.md now without a flood of nine errors. I clear my log before such tests, and I wll see if today more of those declaration mismatch errors are logged or of they were fixed in the same update.

**Comment by bernd-wechner** [comment]
NO I'm flooded with this message:

'''
Declaration of OCA\CMSPico\Http\PicoAssetResponse::cacheFor(int $cacheSeconds): OCA\CMSPico\Http\PicoAssetResponse should be compatible with OCP\AppFramework\Http\Response::cacheFor(int $cacheSeconds, bool $public = false) at /var/www/html/nextcloud/apps/cms_pico/lib/Http/PicoAssetResponse.php#104
'''
