### ISSUE TITLE
Cannot copy themes

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/cms_pico#137]
Odd. Here's a video of the effort:

https://mega.nz/file/VK4zXAIQ#itM8gfZ4VJwXkO8b9haMAE4xpBnAAhJqhNb7Corg098

It just reports: `A unexpected error occured while performing this action. Please check Nextcloud's logs.`

Which as two typos (as an aside) - `An unexpected` and `occurred`

But by the by, there is nothing in the Nextcloud logs at all. So, appreciate a diagnostic tip, how to identify the error.

I know this did work before. And I know I upgraded to NC 19.0.2 in the interim. But have proof of nothing. As nothing in the Nextcloud log.

**Comment by PhrozenByte** [comment]
Make sure that your webserver resp. PHP process has full write permissions to your Nextcloud's `data/` as well as Pico CMS for Nextcloud's `apps/cms_pico/appdata_public/` directories - including all its sub-directories. Also check your PHP logs. Sometimes PHP fails to properly detect these issues and silently bails... 

PS: your video doesn't actually show what I assume you wanted to show us :wink:

**Comment by bernd-wechner** [comment]
Oops, sorry about the link bungle. Fixed that.

Re: permissions. From phpinfo:

```
Environment
Variable | Value
-- | --
TEMP | /tmp
TMPDIR | /tmp
TMP | /tmp
PATH | /usr/local/bin:/usr/bin:/bin
HOSTNAME | no value
USER | www-data
HOME | /var/www
```

From bash:
```
$ grep datadirectory /var/www/html/nextcloud/config/config.php 
  'datadirectory' => '/data/nextcloud',
$ ls -ld /data/nextcloud
drwxrwx--- 7 www-data www-data 4096 Aug 29 15:49 /data/nextcloud
$ ls -ld /data
drwxr-xr-x 8 root root 4096 Aug 21 19:52 /data
$ ls -ld /var/www/html/nextcloud/apps/cms_pico/appdata_public/
drwxr-xr-x 4 www-data www-data 4096 Aug 22 15:33 /var/www/html/nextcloud/apps/cms_pico/appdata_public/
$ ls -l /var/www/html/nextcloud/apps/cms_pico/appdata_public/
total 8
drwxr-xr-x 3 www-data www-data 4096 Aug 22 15:33 plugins
drwxr-xr-x 3 www-data www-data 4096 Aug 22 16:44 themes
$ ls -l /var/www/html/nextcloud/apps/cms_pico/appdata_public/themes/
total 4
drwxr-xr-x 4 www-data www-data 4096 Aug 22 16:44 FRelq0qGNp
$ ls -l /var/www/html/nextcloud/apps/cms_pico/appdata_public/themes/FRelq0qGNp/
total 8
drwxr-xr-x 7 www-data www-data 4096 Aug 22 15:33 default
drwxr-xr-x 7 www-data www-data 4096 Aug 22 16:47 tidy
$ ls -l /var/www/html/nextcloud/apps/cms_pico/appdata_public/themes/FRelq0qGNp/default/
total 48
-rw-r--r-- 1 www-data www-data 3826 Aug 22 15:33 CHANGELOG.md
-rw-r--r-- 1 www-data www-data 1085 Aug 22 15:33 LICENSE
-rw-r--r-- 1 www-data www-data 5381 Aug 22 15:33 README.md
-rw-r--r-- 1 www-data www-data 1188 Aug 22 15:33 composer.json
drwxr-xr-x 2 www-data www-data 4096 Aug 22 15:33 css
drwxr-xr-x 2 www-data www-data 4096 Aug 22 15:33 font
drwxr-xr-x 2 www-data www-data 4096 Aug 22 15:33 icon
drwxr-xr-x 2 www-data www-data 4096 Aug 22 15:33 img
-rw-r--r-- 1 www-data www-data 3584 Aug 29 16:47 index.twig
drwxr-xr-x 2 www-data www-data 4096 Aug 22 15:33 js
-rw-r--r-- 1 www-data www-data  976 Aug 22 15:33 pico-theme.yml
```

Looks in order to me. I wonder if there's something I can se tin phph.ini to boost the debug logging. I'll check and report back.

**Comment by bernd-wechner** [comment]
No news?

**Comment by PhrozenByte** [comment]
Open the web developer tools in your browser using F12, open the Network tab and try copying the theme again. Check the HTTP response of the copy request. Also check your PHP error log.

**Comment by bernd-wechner** [comment]
Well the Network tab reveals something. There's a `501 Not Implemented` response. I see nothing in the PHP error logs. But am trying to work out how to test that (i.e. that error logging is working at all)

**Comment by PhrozenByte** [comment]
It's rather unlikely that `501 Not Implemented` is caused by Pico CMS for Nextcloud or Nextcloud, but rather by your webserver or something in-between (like a proxy). See https://docs.nextcloud.com/server/19/admin_manual/issues/general_troubleshooting.html#unable-to-update-contacts-or-events (even tough it's about calendar it might be the same issue)

**Comment by bernd-wechner** [comment]
Stalebot begone!  ;-)

I have further traced this. When the copy button is clicked Nextcloud sends a CLONE request. There's a problem there. I can't find it documented or specced anywhere. The closest I come is WebDav specs like:

https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/rzaie/rzaiewebdav.htm

but none contain CLONE. COPY yes, CLONE no. 

And 501 not implemented does indeed come from my web browser because indeed CLONE is not implemented.

So my question is, to whoever wrote that request:

1. This presumably works on Apache? Nginx?
2. Where is that request method documented? If anywhere?

**Comment by PhrozenByte** [comment]
If any software interferes with HTTP requests it's an issue with that particular software interfering with the HTTP request, not the software sending the request. The HTTP standard doesn't define a final list of request methods.

**Comment by bernd-wechner** [comment]
Sure, but is the CLONE request documented anywhere, or invented for this purpose. I presume one way or the other that Apache and Nginx let it pass through a reverse proxy config unaltered or you wouldn't be using it. This feature is rather optional and not a hug drama to be broken and my main drive here is learning. Understanding what's going on. 

Part of that is understanding the origins of that request. There are certainly documents all over the web listing standard HTTP requests and WebDav extensions.  What you're suggesting is the HTTP protocol makes no specifications of what request methods are allowed or not and the world is free to define any request method as long as both client (requesting with it) and server (the receiver of the request) implement it.

Salient question I'm curious about still are:

Is CLONE defined anywhere, does it have any precedents or is it invented here for this app?

**Comment by bernd-wechner** [comment]
Did Stalebot kill out conversation? Die stalebot, die.

**Comment by PhrozenByte** [comment]
Neither nor, neither is it any standard nor did we invent it here, a lot other projects with RESTful APIs use it.

**Comment by bernd-wechner** [comment]
I'd love some examples or a reference TBH.
