### ISSUE TITLE
problems with local external storage?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/cms_pico#141]
Hi, I just installed picocms to try it out and got the following error message while trying to create a new test-site with a user.
Which is strange because my user has the permission to create folders in there.
(I am using local external storage with picocms 1.0.9 on NC19.0.2)
Please tell me if you need more infos (and please which ones)

`{"reqId":"rDCUL26nlqEJ3R9F69Yl","level":2,"time":"2020-09-11T11:22:34+02:00","remoteAddr":"87.123.152.204","user":"Simon","app":"cms_pico","method":"POST","url":"/apps/cms_pico/personal/websites","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"No create permission for folder","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/cms_pico/lib/Files/StorageFolder.php","line":143,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Service/TemplatesService.php","line":261,"function":"newFolder","class":"OCA\\CMSPico\\Files\\StorageFolder","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Service/WebsitesService.php","line":142,"function":"installTemplate","class":"OCA\\CMSPico\\Service\\TemplatesService","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Controller/WebsitesController.php","line":112,"function":"createWebsite","class":"OCA\\CMSPico\\Service\\WebsitesService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"createPersonalWebsite","class":"OCA\\CMSPico\\Controller\\WebsitesController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1012,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","Line":171,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36","version":"19.0.2.2","id":"5f5b439e830f1"}`

**Comment by PhrozenByte** [comment]
> OCP\Files\NotPermittedException: No create permission for folder

Make sure that your webserver resp. PHP process actually has permission to read & write on the directory in question.

**Comment by szaimen** [comment]
Hi @PhrozenByte thank your for the answer. Yes, my webserver has access to the location in question since the folder creation and storage access for that user on that local-external-storage works without any problem (in the files app). This is why I assumed an issue with the cms_pico app in the first place...

**Comment by szaimen** [comment]
Okay, strange that I didn't get a notification, that the stale bot commented :D

**Comment by szaimen** [comment]
@PhrozenByte it seems like here are some information missing becaue I don't consider this a question. 
What information can I provide to you to make this issue solvable?

**Comment by szaimen** [comment]
I made a screenrecording:
[Screenrecording.zip](https://github.com/nextcloud/cms_pico/files/5252314/Screenrecording.zip)

**Comment by PhrozenByte** [comment]
Unfortunately I'm unable to provide any more help here: Nextcloud (read: the PHP process) is complaining that it doesn't have permission to create a new folder. That's neither an issue with Nextcloud nor the app. Check the permissions again and if it still doesn't work, contact your server admin.

**Comment by szaimen** [comment]
As you could see in my video, Nextcloud (the files app) is actually able to create a folder there. Only the cms_pico app isn't able to do so. So I still think that this is an issue with the cms_pico app. 
And btw: the permissions should be correct: `www-data:www-data 770` are the permissions for the folder where cms_puco fails to create a new subfolder. So the webserver does have create permissions. Does the PHP process need extra permissions?

**Comment by parajbs** [comment]
I have the same problem with Nextcloud 20 RC1! Also get the error "The website's path is stored on a non-local storage" when creating a website!

But I found out that it works if you don't enable "server-side encryption"!

But since I need "server-side encryption" enabled, I think it's a shame that it doesn't work!

But maybe it's just a BUG! And I can still hope!
Or the programmer can change the code so that one also has a path outside of the nextcloud files (example: / var / www / websites /
            >> and << nextcloud-path: / var / www / html)! And then mount this path via external-storage local!

**Comment by szaimen** [comment]
@parajbs this has nothing to do with my issue. Please open a new one. For me the server-side-encryption isn't enabled and it still doesn't work although I am using local external storage and the rights are set correctly.

**Comment by PhrozenByte** [comment]
I still can't reproduce this. Nextcloud is reporting that it has no permission to create new folders, so I can just hint you once again to check all folders in between whether PHP has permission to create folders. This must also include the base path of the external storage.

**Comment by szaimen** [comment]
I still think that this is an issue with your app since creating folder works without any issue with the files app.

But since you are obviously not interested in fixing this bug, I go ahead and close this issue. Fighting against the stale bot is not worth it.

**Comment by szaimen** [comment]
@PhrozenByte fyi: I've just experienced a comparable bug in NC21 which seems to have the same root cause:
https://github.com/nextcloud/server/issues/25787#issuecomment-785337695

**Comment by szaimen** [comment]
@PhrozenByte there was a PR in the server repository created that fixes my issues with read only root folder and the following was suggested about this issue here: https://github.com/nextcloud/server/pull/26396#issuecomment-811844604
> Seems to be a similar case where the pico_cms app would need a related fix to get the node of the parent directory first before creating the file, so I'd suggest to open an issue in the apps repo.
