### ISSUE TITLE
Allow setting/modifying of nextclouds CSP header for embedded content

### ISSUE THREAD

**Issue by ansorg** [nextcloud/cms_pico#142]
I'm running cms_pico on Nextcloud 19.0.2.
I have added the PicoEmbed plugin from https://github.com/s4ad/PicoEmbed
When I add such an [embed] block into a pico cms content it will render HTML with the embedding IFrame as expected.

But the IFrame will not show any content due to 
`Refused to frame 'https://www.youtube.com/' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.`

1) Would it be possible for cms_pico to somehow modify the Nextcloud default CSP policy to include a "frame-src" attribute? 
2) And have an option in the cms_pico admin to add urls to be used in the "frame-src" CSP attribute?

Some research brought up this code that seems to do something similar as (1) https://github.com/owncloudarchive/jsxc.chat/blob/master/appinfo/app.php

**Comment by PhrozenByte** [comment]
Yes, this is possible, Pico CMS for Nextcloud already modifies Nextcloud's CSP, themes wouldn't be able to use any assets otherwise. However, allowing this in the way you described would yield huge potential security issues, because we can't expect most Nextcloud admins to know what all this is about. The only way to implement this safely is hosting websites on different domains, something that is planned already, see #83

**Comment by ansorg** [comment]
ok, got it. And thanks for pointing me to PicoContentSecurityPolicy for a temporary solution :-)

**Comment by GregorKopka** [comment]
So to get this right: PicoCMS for NextCloud is currently unable to create a site that embeds youtube videos?

**Comment by PhrozenByte** [comment]
With the default theme? No. But you can add support for YouTube videos to your theme (simply use a meta header that holds just a video id, validate it in your theme using a regular expression and you're safe) or write a plugin to allow free placement inside content files.

**Comment by GregorKopka** [comment]
> With the default theme? No. But you can add support for YouTube videos to your theme (simply use a meta header that holds just a video id, validate it in your theme using a regular expression and you're safe) or write a plugin to allow free placement inside content files.

Problem is that IFRAMEs will not render because CSP. 
There should be a way to configure this to make PicoCMS for NextCloud really useful.
