### ISSUE TITLE
What is a CLONE request?

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/cms_pico#144]
Directly derived from: https://github.com/nextcloud/cms_pico/issues/137

which was closed by stalebot and therefore is beneath the radar. I am keen to understand the use of the CLONE request method used by the cms_pico app. It is used here:

https://github.com/nextcloud/cms_pico/blob/master/appinfo/routes.php

I can't find a formal list of WEBDAV extensions, in fact there may not be one, but variosu source slist extensions:

https://www.tutorialspoint.com/http/http_methods.htm
https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/rzaie/rzaiewebdav.htm
https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModWebDAV

cms_pico seems in routes.php to use:

- GET
- POST
- DELETE
- CLONE

Only the last one seems undocumented anywhere.  My questions

1. Is it documented anywhere? 
2. or was it invented here ....?
3. I presume Apache and Nginx pass it through unaltered. True? 
4. Why not use COPY, which does seem widely documented?

**Comment by PhrozenByte** [comment]
Please refer to https://github.com/nextcloud/cms_pico/issues/137
