### ISSUE TITLE
Pages blank after server upgrade to 19.0.3

### ISSUE THREAD

**Issue by Bockeman** [nextcloud/cms_pico#145]
I reported this here
https://github.com/nextcloud/desktop/issues/2466
but perhaps it is a cms_pico issue

**Comment by PhrozenByte** [comment]
Reload all of your themes by clicking the button next to the theme listing in your Nextcloud admin settings.

**Comment by Bockeman** [comment]
Thanks @PhrozenByte   That solved the issue.

Specifically:
I had previously tried to reload the themes, but that generated errors logged in nextcloud/desktop#2466

sudo -u apache php /var/www/html/verivault/console.php files:scan-app-data 
  did not appear necessary
sudo -u apache php /var/www/html/verivault/console.php files:cleanup
  did not appear necessary

I had also run the repair at some earlier stage (possibly prior to the upgrade), nonetheless, I did as you suggested:
sudo -u apache php /var/www/html/verivault/console.php maintenance:repair
  ...
   - Preparing app data of Pico CMS for Nextcloud
       - Checking Pico CMS requirements ??
       - Syncing Pico CMS app data folder ??
       - Copying Pico CMS config ??
       - WARNING: Replacing Pico CMS config file "config.yml.template"
       - Registering Pico CMS templates ??
       - WARNING: Replacing Pico CMS system template "empty"
       - WARNING: Replacing Pico CMS system template "sample_pico"
       - Publishing Pico CMS themes ??
       - WARNING: Replacing Pico CMS system theme "default"
       - Keeping Pico CMS custom theme "astral"
       - Keeping Pico CMS custom theme "bitsandpieces"
       - Keeping Pico CMS custom theme "clutter"
       - Keeping Pico CMS custom theme "dimension"
       - Keeping Pico CMS custom theme "genealogy"
       - Keeping Pico CMS custom theme "magazine"
       - Keeping Pico CMS custom theme "sample"
       - Keeping Pico CMS custom theme "veriserve"
       - Publishing Pico CMS plugins ??
       - WARNING: Replacing Pico CMS system plugin "PicoDeprecated"
       - Keeping Pico CMS custom plugin "Clutter"
       - Keeping Pico CMS custom plugin "PicoSearch"
  ...

I then reloaded all the themes, which now went ahead successfully.

Then I visited my site pages, and all is back as before.  Thanks again.

I am however curious, what in your opinion went wrong?  Was it something corrupt in my files somewhere, or is this purely as a consequence of upgrading to 19.0.3 (and therefore everyone may need to follow this procedure).  Perhaps we can only tell if others experience the same problem and are kind enough comment or "me also".
_[I suggest waiting a bit for possible responses before closing this issue.)_

**Comment by PhrozenByte** [comment]
When updating the app or Nextcloud, database and filesystem get out of sync. That's totally normal. When updating, the app automatically triggers a rebuild from filesystem. However, for some reason this failed for you - maybe the update was interrupted by another faulty app. Anyway, you can trigger the exact same rebuild by running `occ maintenance:repair`.

**Comment by Bockeman** [comment]
No one else has posted with similar problems, so I suspect this was a one-off out-of-sync issue, as you @PhrozenByte suggested.
In any case, the `occ maintenance:repair` solved it for me.  Thanks.
