### ISSUE TITLE
Extension cannot be removed or re-added anymore

### ISSUE THREAD

**Issue by sm8ps** [nextcloud/cms_pico#146]
The following happened with Pico-CMS 1.0.10 on NC 19.0.3.

I imported the Pico extension PicoUICarousel. In the course of playing around with the source code, I added an empty `echo ;` statement which is a syntax error in PHP as I found out afterwards.

As far as I remember, the extension was *automatically* removed from the list of activated extensions. It does show up in the list of available extensions but cannot be re-added as NC says that the extension already exists.

How can I remove that extension?

**Comment by PhrozenByte** [comment]
Remove the `/apps/cms_pico/appdata_public/plugins/<random string>/PicoUICarousel` folder.

**Comment by sm8ps** [comment]
Thanks for your quick answer, @PhrozenByte ! The problem is that after removing the folder, I cannot re-add the extension because NC still claims that the extension already exists. To be precise, here is what I did:

1. remove the folder
2. reboot the whole server
3. add the folder again
4. import the extension from Pico/NC

Somehow the name seems to be stuck in PHP. Could this be related to caching? If so, can (this part of) the cache be cleared? I am totally at loss here and would be very grateful for some help. Thanks in advance!

**Comment by PhrozenByte** [comment]
Try running `occ maintenance:repair`, this should rebuild all themes and plugins from scratch.

**Comment by sm8ps** [comment]
Excellent, that worked! The obsolete extensions are unlisted and can be re-added.

It is worth noting that any extension with syntax errors  seems to be trapped in this state.

Thank you very much, @PhrozenByte for your quick and efficient help!

**Comment by PhrozenByte** [comment]
> It is worth noting that any extension with syntax errors seems to be trapped in this state.

I'll look into this and maybe re-label this as bug then. However, time's very limited right now, so it might take some time. Thanks for reporting!

**Comment by PhrozenByte** [comment]
You are indeed right, this is a bug. PHP syntax errors weren't caught properly, leading to this undefined state.Thanks for the catch @sm8ps :+1:

**Comment by sm8ps** [comment]
Great! This proves once again that even a blind squirrel finds a nut once in a while. (: 

Keep up the good work!
