### ISSUE TITLE
Any way to load Javascript (notwithstanding Content Security Policy)?

### ISSUE THREAD

**Issue by sm8ps** [nextcloud/cms_pico#147]
Hi all! I am struggling with getting some extensions to work that depend on external Javascripts (e.g. [Pico UI: Carousel](https://github.com/bigicoin/PicoUI)). Any way that I have tried, Content Security Policy seems to prohibit the usage of external Javascripts as can be seen in the web console of Firefox.

It [seems](https://debianforum.de/forum/viewtopic.php?t=164866) that the function 'addSecurityHeaders' in '/lib/private/legacy/response.php' sets the respective HTTP header unconditionally and independently of the web server configuration.

It would be great to get around this restriction because limiting Pico to a pure text blog would leave out some interesting possibilities.

**Comment by sm8ps** [comment]
Oh, right! I did read through #99 but could not grasp all the information there. It does all make perfect sense now. Thanks a lot.

If you don't mind, I keep this issue open until I get to grips with it. Then I shall add a quick resume for others reference.

IMHO it would make sense to collect such experience reports in the wiki but AFAICT there is no way to issue PRs to Github wikis. Otherwise I would be glad to help.

**Comment by sm8ps** [comment]
OK, that was pretty easy -- at least looking back to it. I had to embed the Javascript and CSS code into the folder of the current theme and then have the respective TWIG file load it by calling it from the `{{ theme_url }}` folder. Thanks a lot for the pointer! Closing this issue now. Maybe others find it helpful, too.

While working I came to think if the restrictions could be loosened in such a way that the `{{ themes_url }}` folder (note the difference, it refers to './cms-pico/themes/') would be available to the individual themes. That way, one would not have keep duplicate copies of assets for each theme. I am assuming here that this should be easily possible and not have adverse effects but I may very well be wrong.

I think this question is not really a separate issue of its own. Would you mind commenting here?

**Comment by PhrozenByte** [comment]
There are no directory restrictions, i.e. you can already use `{{ themes_url }}`, even though the contents of this folder are automatically managed by the app, i.e. you can't add custom files. Just for not having duplicates of the files is not worth the effort.

**Comment by sm8ps** [comment]
Thanks for your answer! I see your point and it even explains a little bit of the inner workings of cms_pico/NC to me. Since Pico is all flat file based, I have not seen very clear where the boundaries of this concept lie within the realm of Nextcloud.

Thanks also and especially for your efforts with cms_pico! I am looking forward to getting it productive for my use case.
