### ISSUE TITLE
Default theme not loading, issue with directory when Nextcloud not in web-root

### ISSUE THREAD

**Issue by poVoq** [nextcloud/cms_pico#15]
Seems like there is some issue loading the theme files when nextcloud is not in the web-root.

My nextcloud setup is like the following:
www.mysite.com/nextcloud/ (www.mysite.com runs another web-site)

This plugin with mod_rewrite (on a share host, only .htaccess and thus no mod_proxy I think) shows pico user websites under
www.mysite.com/sites/picouserwebsite
(as explained in the docs, at first I was a bit confused that it isn't www.mysite.com/nextcloud/sites/picouserwebsite but now I actually like it that way)

However it just renders the plain html as converted from the markdown files (including pictures from the assets folder).

When I check the web-console it tells me that it fails to load:
modernizr-2.6.1.min.js, style.css & fontello.css
as it looks for them under:
www.mysite.com/apps/cms_pico/Pico/themes/default/
www.mysite.com/apps/cms_pico/Pico/themes/default/scripts/

and not
www.mysite.com/nextcloud/apps/cms_pico/Pico/themes/default/
like it should.

**Comment by daita** [comment]
sorry, have no idea why this issue were closed.

**Comment by poVoq** [comment]
can conform that the theme is loading in 0.95. Thanks a lot.
