### ISSUE TITLE
'Limit to groups' is not working

### ISSUE THREAD

**Issue by fenvarien** [nextcloud/cms_pico#150]
In a clean installation of nextcloud 20.0.1. and the latest pico cms app I can't use the "limit to groups" setting, because is never stops to show "Loading groups…".
 
I can't type into the field and therefore it is not possible to select a group. Is there a known workaround for this behavoir? 
Currently there are only 3 groups and 12 users.

![picocms](https://user-images.githubusercontent.com/644596/98710520-0b77fc00-2384-11eb-8fd3-fcfb7e963bda.PNG)

**Comment by PhrozenByte** [comment]
A install with 3 groups and 12 users is no "clean" install, isn't it? :wink: Unfortunately I can't reproduce this. Please check your Nextcloud log, your webserver's resp. PHP's `error.log` and if nothing is found in the logs, open the Developer Tools in your browser (usually by hitting <kbd>F12</kbd>). Check the console for errors. Switch to the Network tab and search for the `/ocs/v2.php/cloud/groups/details` request. The group selection component is a built-in component of Nextcloud, i.e. it should appear broken elsewhere in your Nextcloud, too.

**Comment by fenvarien** [comment]
Thanks for your answer and support!
There's not error shown in the network tab. But I can see the following problem in the console:

Uncaught TypeError: Cannot read property 'setupGroupsSelect' of undefined
    at HTMLDocument.<anonymous> (admin.js?v=50ece2ef-0:282)
    at l (main.js?v=50ece2ef-0:1)
    at Object.add [as done] (main.js?v=50ece2ef-0:1)
    at m.fn.init.m.fn.ready (main.js?v=50ece2ef-0:1)
    at e.fn.init.m.fn.init (main.js?v=50ece2ef-0:1)
    at new e.fn.init (main.js?v=50ece2ef-0:1)
    at m (main.js?v=50ece2ef-0:1)
    at OCA.CMSPico.LimitGroupsForm.prepare (admin.js?v=50ece2ef-0:281)
    at HTMLFormElement.<anonymous> (admin.js?v=50ece2ef-0:314)
    at Function.each (main.js?v=50ece2ef-0:1)

After trying and reloading the pico cms setttings page several times and waiting for some minutes the error is gone and I'm able to select groups. The funtionality itself works great, just "selecting the groups" in the menu seems to have a problem.

**Comment by PhrozenByte** [comment]
Sounds to me like an issue with the JavaScript cache. Try `occ maintenance:repair` when the issue persists.
