### ISSUE TITLE
cms_pico lost in latest update.  

### ISSUE THREAD

**Issue by rollanders** [nextcloud/cms_pico#154]
I am on NC 20.0.2. Wanted to update all apps before upgrading to 20.0.3. After starting update NC was stuck in maintenance mode. I turned it off from the panel. I now have a notice that  there is an update for cms_pico to version 1.0.12. But cms_pico is no longer available in the menu or in the apps-list. 
In the logs I have these errors (I copied some of them)

[PHP] Error: Error: rmdir(/var/www/nextcloud/apps/cms_pico): Directory not empty at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#178 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "rmdir(/var/www/ ... y", "/var/www/nextcl ... p", 178, {dir: "/var/www/ ... }})
 1. /var/www/nextcloud/lib/private/legacy/OC_Helper.php line 178
    rmdir("/var/www/nextcloud/apps/cms_pico")
 2. /var/www/nextcloud/lib/private/Installer.php line 347
    OC_Helper::rmdirr("/var/www/nextcloud/apps/cms_pico")
 3. /var/www/nextcloud/lib/private/Installer.php line 198
    OC\Installer->downloadApp("*** sensitive parameter replaced ***", false)
 4. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 532
    OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "updateApp")
 7. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "updateApp")
 8. /var/www/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "updateApp", OC\AppFramework\ ... {}, {action: null,ap ... "})
 9. /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/settings/apps/update/cms_pico")
10. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /settings/apps/update/cms_pico
from 192.168.1.1 by NCadmin at 2020-12-10T09:49:55+01:00

----

[PHP] Error: Error: rmdir(/var/www/nextcloud/apps/cms_pico/appdata_public): Directory not empty at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#172 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "rmdir(/var/www/ ... y", "/var/www/nextcl ... p", 172, {dir: "/var/www/ ... }})
 1. /var/www/nextcloud/lib/private/legacy/OC_Helper.php line 172
    rmdir("/var/www/nextcl ... c")
 2. /var/www/nextcloud/lib/private/Installer.php line 347
    OC_Helper::rmdirr("/var/www/nextcloud/apps/cms_pico")
 3. /var/www/nextcloud/lib/private/Installer.php line 198
    OC\Installer->downloadApp("*** sensitive parameter replaced ***", false)
 4. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 532
    OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "updateApp")
 7. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "updateApp")
 8. /var/www/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "updateApp", OC\AppFramework\ ... {}, {action: null,ap ... "})
 9. /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/settings/apps/update/cms_pico")
10. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /settings/apps/update/cms_pico
from 192.168.1.1 by NCadmin at 2020-12-10T09:49:55+01:00

----
[PHP] Error: Error: unlink(/var/www/nextcloud/apps/cms_pico/appdata_public/plugins/jhp6vkoKdF/PicoEmbed/.git/hooks/fsmonitor-watchman.sample): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#174 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "unlink(/var/www ... d", "/var/www/nextcl ... p", 174, {dir: "/var/www/ ... }})
 1. /var/www/nextcloud/lib/private/legacy/OC_Helper.php line 174
    unlink("/var/www/nextcl ... e")
 2. /var/www/nextcloud/lib/private/Installer.php line 347
    OC_Helper::rmdirr("/var/www/nextcloud/apps/cms_pico")
 3. /var/www/nextcloud/lib/private/Installer.php line 198
    OC\Installer->downloadApp("*** sensitive parameter replaced ***", false)
 4. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 532
    OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "updateApp")
 7. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "updateApp")
 8. /var/www/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "updateApp", OC\AppFramework\ ... {}, {action: null,ap ... "})
 9. /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/settings/apps/update/cms_pico")
10. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /settings/apps/update/cms_pico
from 192.168.1.1 by NCadmin at 2020-12-10T09:49:55+01:00

**Comment by PhrozenByte** [comment]
Nextcloud fails to delete the old app folder. Try deleting `apps/cms_pico` and reinstall the app.

**Comment by rollanders** [comment]
Thanks it worked.
