### ISSUE TITLE
Access is denied to a cms_pico site after last update

### ISSUE THREAD

**Issue by rollanders** [nextcloud/cms_pico#155]
After last update access is denied to a cms_pico site from the NC internal menu. 
I have made a cms_pico site at  https://mysite.dedyn.io/sites/gemenskap
This URL is OK. I can access it as an external site. 
I add this URL to the External site app and choose to position the icon in the Header section. 
When I clique on the External site icon in the header menu, the page https://mysite.dedyn.io/apps/external/7 is opened but the page is greyed and show that mysite.dedyn.io denies access
This behaviour occurred after last update. 
The External site app works normally with other true external URLs so I think this is a cms_pico issue

I find no error in the log that I think is related to this issue.

**Comment by PhrozenByte** [comment]
Try changing https://github.com/nextcloud/cms_pico/blob/42eb83bf3aacbe50adbbb7c52d7d1199ac80e9d5/lib/Http/PicoContentSecurityPolicy.php#L85 to 

```php
	protected $allowedFrameAncestors = ['\'self\''];
```

Does this solve your issue?

**Comment by rollanders** [comment]
Japp. It worked. 
Thanks
Roland

**Comment by PhrozenByte** [comment]
That's weird because it means that it should not have worked before :confused:

Aaanyway... Will be fixed in the next release.
