### ISSUE TITLE
Changing theme generates internal server error

### ISSUE THREAD

**Issue by dosch** [nextcloud/cms_pico#159]
I tried several different themes from the official theme website of PicoCMS, but every time I move away from the default theme, my website becomes unavailable due to an 'internal server error'

**What I did:**
- I downloaded a theme with `wget` to my theme folder. 
- I unzupped the master.zip file.
- I made sure that the directory containing the index.twig file was placed in `./themes/`
- I went to the Nextcloud backend and confirmed that the theme showed up in the admin panel for PicoCMS
- I activated the theme there.
- I went to the personal pref pane for PicoCMS and changed the theme of my site there
- I reload the website: boom, error.

This happens in the logs:

```
[cms_pico] Error: OCA\CMSPico\Exceptions\PicoRuntimeException: Unknown "root" filter. at <<closure>>

0. /var/www/nextcloud/apps/cms_pico/lib/Service/WebsitesService.php line 282
   OCA\CMSPico\Service\PicoService->getPage(OCA\CMSPico\Model\Website {})
1. /var/www/nextcloud/apps/cms_pico/lib/Controller/PicoController.php line 108
   OCA\CMSPico\Service\WebsitesService->getPage("documentation", "software", "[REDACTED]", false)
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\CMSPico\Controller\PicoController->getPage("documentation", "software", false)
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\CMSPico\Controller\PicoController {}, "getPage")
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\CMSPico\Controller\PicoController {}, "getPage")
5. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\CMSPico\\C ... r", "getPage", OC\AppFramework\ ... {}, {page: "software ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({page: "software ... "})
7. /var/www/nextcloud/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {page: "software ... "})
8. /var/www/nextcloud/lib/base.php line 1012
   OC\Route\Router->match("/apps/cms_pico/ ... e")
9. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

GET /apps/cms_pico/pico/documentation/software
from [REDACTED] by [REDACTED] at 2021-02-17T20:36:51+00:00
```

- Reverting to the default theme makes the website accessible again.

**Comment by PhrozenByte** [comment]
This is an error with your custom 3rd-party theme (Twig error `Unknown "root" filter`). Looks like your theme uses a custom Twig filter `root`. I assume your theme requires a plugin to work, please check the theme's install instructions (check the theme's `README.md`). Since you didn't provide any information about the 3rd-party theme you try to use I can only guess.

**Comment by dosch** [comment]
hey @PhrozenByte, I tried several themes:
- https://github.com/alan-luo/clutter
- https://github.com/lostkeys/Bits-and-Pieces-Theme-for-Pico

They didn't work. 

But as a new test I just tried [SimpleTwo](https://github.com/sonst-was/simpleTwo) and that one did not gave me any errors.

**Comment by PhrozenByte** [comment]
Clutter requires a 3rd-party plugin, see the `plugins` folder of that theme. For Bits and Pieces I can't see a reason why it shouldn't work. If you have any issues with 3rd-party themes and plugins, please refer to their respective developers to receive help.

**Comment by dosch** [comment]
Thnx @PhrozenByte 

I will contact the devs. Seems that it is indeed related to the themes, but that PicoCMS for NC is working good. Thnx for your time and continued development
