### ISSUE TITLE
Include additional templates (for a wiki etc.)?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/cms_pico#16]
Would be cool if there was a more wiki like template that makes it easy for users to quickly make a wiki.
At best if this plugin was also included:
https://github.com/arckauss/Pico-Categorized-Pages

And maybe:
https://github.com/mwgg/Pico-Search

**Comment by geiseri** [comment]
It would be good to have at least a "blank" template with no header or footer so you can have an unbranded site.

**Comment by daita** [comment]
I will see to add a blank template, however for any other plugins/templates, you can still add them from the Admin Settings Page

**Comment by geiseri** [comment]
I know we can add our own plugins and templates but there is a certain comfort I take in the knowledge that the templates and plugins selected by the cms_pico authors are safe to use.

**Comment by daita** [comment]
I made a blank template.

However, the idea of distributing plugins within the app will require too much work (UI so Admin can enable/disable plugins) for something that does not really fit the concept of picocms.
