### ISSUE TITLE
plugin php error messages after update to 1.0.14

### ISSUE THREAD

**Issue by muranava** [nextcloud/cms_pico#160]
hi
not sure if i should ask here or the plugin author but after updating to Pico CMS for Nextcloud  1.0.14 i am getting an error message about php undefined index issue about a plugin called PicoRSS.php (https://github.com/HLSiira/PicoPlugins).
the plugin still seems to work though.
thx

**Comment by PhrozenByte** [comment]
Please refer to the developer of the 3rd party plugin to get help :smiley:

**Comment by muranava** [comment]
okay the developer found the problem https://github.com/HLSiira/PicoPlugins/issues/1#issuecomment-788375310
