### ISSUE TITLE
False positive: The websites path is stored on a non local storage

### ISSUE THREAD

**Issue by gpgmailencrypt** [nextcloud/cms_pico#161]
AFAIK this error message is the result of trying to store on an encrypted storage.
On a freshly installed nextcloud 20.0.8 with server-side encryption switched on, but with home storage encryption **switched off** (see below) I get this error message. I checked it on the server side, files will definitely not be encrypted. Deactivating encryption  solves the problem

So it seems to be a false positive.

![settings](https://user-images.githubusercontent.com/13087633/109685563-aab63e80-7b81-11eb-950a-81a4a57d33d3.png)

**Comment by PhrozenByte** [comment]
This isn't really about whether a particular file is actually encrypted or not, but about how Nextcloud accesses files. As soon as you enable server-side encryption, Nextcloud no longer accesses files directly, but performs instructions on temporary files instead. If you don't encrypt your home storage the temporary file is just a copy of the original file, but it's still not the original file. Pico CMS for Nextcloud (or any other app) won't ever see the original file. We can't do anything about this, it's just how Nextcloud implemented server-side encryption.

**Comment by gpgmailencrypt** [comment]
Thanks for the info. But nevertheless, theoretically picocms would work correctly under these circumstances. Wouldn't it be a good idea to either reduce the error to a warning or add a "I know what I'm doing"/"Continue on your own risk"-button?

**Comment by PhrozenByte** [comment]
Pico requires direct file access - which is, as explained above, no longer possible when the admin enables server-side encryption, no matter whether the file is actually encrypted or not.
