### ISSUE TITLE
trying to delete a site results in error

### ISSUE THREAD

**Issue by muranava** [nextcloud/cms_pico#162]
hi when i try to delete a site , i get an error and the site cannot be deleted
in logs:
---
<s>OCA\CMSPico\Exceptions\PicoRuntimeException: Uncaught Twig\Error\LoaderErrorUncaught Twig\Error\LoaderError: Unable to find template "single.twig" (looked into: /var/www/nextcloud/apps/cms_pico/appdata_public/themes/cycyaOWclF/default).</s>
---

**Comment by PhrozenByte** [comment]
Please provide the stack trace of the exception from your logs.

**Comment by muranava** [comment]
hi
it's stange i still have the "can't delete site behavior" but the logs are not showing anything?

**Comment by muranava** [comment]
please ignore the error code i pasted above it is from another event; but i still have problem that i can't delete sites and there is no log message for this?
i tried enabling debug = 0 in config.php for nextcloud but still no log message.

**Comment by muranava** [comment]
to add -  the "cant delete" behavior is happening when i try to delete themes and plugins as well

**Comment by PhrozenByte** [comment]
What exact error are you receiving? Please check your error log, all exceptions should be logged. Also try opening the Web Developer Tools (<kbd>F12</kbd>), switch to Network and check the response of the request in question.

**Comment by muranava** [comment]
the nextcloud logs don't seem to show anything; the Network shows:
--
DELETE |  
scheme | https
host | nextcloud.englishup.me
filename | /apps/cms_pico/personal/websites/17
Status405
Method Not Allowed
VersionHTTP/2
Transferred929 B (0 B size)
Referrer Policyno-referrer
---

**Comment by PhrozenByte** [comment]
This seems to be similar to #137, in which the webserver is causing this issue by blocking the DELETE request. Pico CMS for Nextcloud doesn't respond with a "405 Method Not Allowed" error itself. What are the contents of the response? One from your webserver or from Nextcloud?

**Comment by muranava** [comment]
where can i get "contents of the response" info?

**Comment by PhrozenByte** [comment]
In the Network tab of the Web developer tools by clicking on the request in question and the appropriate sub-tab.

**Comment by muranava** [comment]
ok thanks, i think it is something to do with the webserver as i cannot create any text documents either;

**Comment by muranava** [comment]
hi just reporting back here, it was a modsecurity issue; thanks for the support!
