### ISSUE TITLE
External storage

### ISSUE THREAD

**Issue by matrois** [nextcloud/cms_pico#165]
I only use external storage, allthough it is local. Amongst other things I prevent with external storage write access to the home directory. The users should work in project directory. With this (the use of the app, see https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage_configuration_gui.html) the app cms_pico is not compatible. 

If I add a new site and choose the external storage as destination folder (there is no one with write access, but I am able to choose the external storage) I get an error message: "No create permission for folder"
I have double checked, that there is write permission. I work whole day in that folder... 
For testing I tried to activate write access in home folder. Because the app is working there I think it is incompatible with "external storage".

**Comment by PhrozenByte** [comment]
Sounds like a duplicate of #141, which is caused by an (currently unfixed) bug in Nextcloud.

**Comment by matrois** [comment]
@PhrozenByte: You are right. I think it is the same bug. Sorry I did not found that one before. 
I do not actually understand why it could be a Nextcloud problem allthough the files app has write access. But that does not matter. If I understood I could solve the problem. That is unfortunately not the case. 

I am not firm in using this github things. Should I close this issue now, because there is another one with the same bug?

**Comment by PhrozenByte** [comment]
Not all bugs show under all circumstances, so in fact the files app might not trigger the bug. The exception isn't thrown by Pico CMS for Nextcloud, but by Nextcloud; we just use Nextcloud's API and can only rely on the things Nextcloud provides us here. You can close this issue yourself if you want to, otherwise it will be closed by Stale bot in about a week.
