### ISSUE TITLE
pages are gone after editing (Nextcloud)

### ISSUE THREAD

**Issue by daniu-de** [nextcloud/cms_pico#166]
Hi,
I installed the pico-CMS plugin and it works nicely. However any page that I edit within Nextcloud is gone after any editing wihtout substantially changing anything
regards

**Comment by PhrozenByte** [comment]
See https://github.com/nextcloud/cms_pico#nextclouds-text-app

**Comment by daniu-de** [comment]
Hi,
thanks - however: do I just need to install markdown editor? I did and now got another error message after editing:

I read the passage about incompatible nextcloud apps however I do not know how to find out which one could be incompatible. I do not have the 2 apps mentioned there.

`OCA\CMSPico\Exceptions\PicoRuntimeException: Uncaught Symfony\Component\Yaml\Exception\ParseExceptionUncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 6 (near "![Nextcloud Logo](%25assets_url%25/image.png)").

    /var/www/*pathtonextcloud*/nextcloud/apps/cms_pico/lib/Service/WebsitesService.php - line 279:

    OCA\CMSPico\Service\PicoService->getPage()

    /var/www/*pathtonextcloud*/nextcloud/apps/cms_pico/lib/Controller/PicoController.php - line 110:

    OCA\CMSPico\Service\WebsitesService->getPage()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\CMSPico\Controller\PicoController->getPage()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/*pathtonextcloud*/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/*pathtonextcloud*/nextcloud/index.php - line 37:

    OC::handleRequest()

	
vor einer Minute
Error	cms_pico	OCA\CMSPico\Exceptions\PicoRuntimeException: Uncaught Symfony\Component\Yaml\Exception\ParseExceptionUncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 6 (near "![Nextcloud Logo](%25assets_url%25/image.png)").

    /var/www/*pathtonextcloud*/nextcloud/apps/cms_pico/lib/Service/WebsitesService.php - line 279:

    OCA\CMSPico\Service\PicoService->getPage()

    /var/www/*pathtonextcloud*/nextcloud/apps/cms_pico/lib/Controller/PicoController.php - line 110:

    OCA\CMSPico\Service\WebsitesService->getPage()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\CMSPico\Controller\PicoController->getPage()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/*pathtonextcloud*/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/*pathtonextcloud*/nextcloud/index.php - line 37:

    OC::handleRequest()

	
vor 2 Minuten
Error	cms_pico	OCA\CMSPico\Exceptions\PicoRuntimeException: Uncaught Symfony\Component\Yaml\Exception\ParseExceptionUncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 6 (near "![Nextcloud Logo](%25assets_url%25/image.png)").

    /var/www/*pathtonextcloud*/nextcloud/apps/cms_pico/lib/Service/WebsitesService.php - line 279:

    OCA\CMSPico\Service\PicoService->getPage()

    /var/www/*pathtonextcloud*/nextcloud/apps/cms_pico/lib/Controller/PicoController.php - line 110:

    OCA\CMSPico\Service\WebsitesService->getPage()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\CMSPico\Controller\PicoController->getPage()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/*pathtonextcloud*/nextcloud/lib/private/Route/Router.php - line 309:

    OC\AppFramework\App::main()

    /var/www/*pathtonextcloud*/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/*pathtonextcloud*/nextcloud/index.php - line 37:

    OC::handleRequest()`

**Comment by PhrozenByte** [comment]
As the error message says: There's a YAML parse error on line 6. Check the content file in question (likely `index.md`). If you've edited the file with Nextcloud Text before, delete and re-create it with a compatible Markdown editor. Unfortunately Nextcloud Text destroys valid Markdown files.
