### ISSUE TITLE
Internal Server Error on navigation to created website 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/cms_pico#168]
Hello there am new to picocms, and I installed it on nextcloud, now I did everything as the guide says but when I navigate to the path to the website its giving me **Internal Server Error**. Here is the log on nextcloud. Thanks

_{"reqId":"YGcD00kyR8rfYcQidS26FgAA1h4","level":3,"time":"2021-04-02T11:45:24+00:00","remoteAddr":"192.168.15.16","user":"Amanuel_ Kumera","app":"index","method":"GET","url":"/index.php/apps/cms_pico/pico/itblogtest","message":{"Exception":"Exception","Message":"Call to undefined method ParsedownExtra::textElements()","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"Error","Message":"Call to undefined method ParsedownExtra::textElements()","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/cms_pico/vendor/picocms/pico/lib/Pico.php","line":1676,"function":"text","class":"ParsedownExtra","type":"->"},{"file":"/var/www/html/nextcloud/apps/cms_pico/lib/Pico.php","line":216,"function":"parseFileContent","class":"Pico","type":"->"},{"file":"/var/www/html/nextcloud/apps/cms_pico/vendor/picocms/pico/lib/Pico.php","line":487,"function":"parseFileContent","class":"OCA\\CMSPico\\Pico","type":"->"},{"file":"/var/www/html/nextcloud/apps/cms_pico/lib/Pico.php","line":108,"function":"run","class":"Pico","type":"->"},{"file":"/var/www/html/nextcloud/apps/cms_pico/lib/Service/PicoService.php","line":149,"function":"run","class":"OCA\\CMSPico\\Pico","type":"->"},{"file":"/var/www/html/nextcloud/apps/cms_pico/lib/Service/WebsitesService.php","line":279,"function":"getPage","class":"OCA\\CMSPico\\Service\\PicoService","type":"->"},{"file":"/var/www/html/nextcloud/apps/cms_pico/lib/Controller/PicoController.php","line":110,"function":"getPage","class":"OCA\\CMSPico\\Service\\WebsitesService","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getPage","class":"OCA\\CMSPico\\Controller\\PicoController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/apps/cms_pico/vendor/erusev/parsedown-extra/ParsedownExtra.php","Line":46},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68","version":"20.0.8.1","id":"6067046d337d4"}

>

**Comment by PhrozenByte** [comment]
Please read the app's `README.md`.
