### ISSUE TITLE
invisible transparent private/public switch in website settings

### ISSUE THREAD

**Issue by Jonas-itquirks** [nextcloud/cms_pico#169]
See Screenshot. The switch works but is invisible, I found out by accident that the switch is even there.
Might also be related to:
https://github.com/nextcloud/deck/issues/2867
https://github.com/nextcloud/viewer/pull/856

Nextcloud 21.0.1
Pico CMS for Nextcloud v1.0.15

![invisible-switch](https://user-images.githubusercontent.com/77517406/116797573-6692dc00-aae7-11eb-8d7b-960ec7218602.png)

**Comment by PhrozenByte** [comment]
Sorry, this kinda got lost :unamused: Can't reproduce it, though. Don't think the mentioned issues are related. Try flushing your caches (run `occ maintenance:repair`).
