### ISSUE TITLE
cannot install app in Nextcloud

### ISSUE THREAD

**Issue by daniu-de** [nextcloud/cms_pico#172]
Hi,

I cannot install the app in Nextcloud while all other apps can be installed: 
 Failed to enable Pico CMS for Nextcloud: The webserver has no permission to create files and folders below "apps/cms_pico/appdata_public/". Make sure to give the webserver write access to this directory by changing its permissions and ownership to the same as of your "data/" directory. Then try again enabling Pico CMS for Nextcloud.

As I don't have shell access to the server I don't know how I should change the rights of the folder and I don't understand why this app is the only one that needs this.

Edit: sorry - forgot important info: using Nextcloud 21.0.2

regards

**Comment by PhrozenByte** [comment]
Please refer to your webserver admin to change the permissions accordingly.

**Comment by daniu-de** [comment]
My admin will not be interested in this issue as it is my Nextcloud installation. I still no not understand why this app is the only one that needs this special setting. It does not make sense to me that the pico cms app needs the server admin to adjust the rights. Especially because I am pretty sure that all nextcloud installation is done by the server and thus should have the appropriate ownership

**Comment by PhrozenByte** [comment]
This question has been answered a couple of times before, please use GitHub's search engine first. To cut a long story short: If you want to publish a website, you need a place for your assets. That's why. Apparently the directory doesn't have the appropriate permissions, otherwise this error wouldn't occur. You'll have to fix this permission issue first, otherwise I'm afraid you won't be able to use Pico CMS for Nextcloud.

**Comment by daniu-de** [comment]
OK: can you tell me how the server creates files (install app in nextcloud) under a user different from the server? I don't see why that should happen and how.
I also just realized that filezilla shows information about the owner of folders. My data directory has exactly the same owner than my apps/cms_pico/appdata_public folder and I would not see any reason why this should be different - the folders were both created the same way: by the server with a php script. Both folders are set to 770

**Comment by daniu-de** [comment]
@PhrozenByte don't see a way to solve that issue and also do not find were this question has been answered a few times.
