### ISSUE TITLE
Attempting to view a private website without being logged in should redirect to login page?

### ISSUE THREAD

**Issue by nooblag** [nextcloud/cms_pico#174]
Hi there,

Like other Nextcloud apps, should it be that if a user is not logged in when trying to access a private website, they're redirected to the login page?

At the moment, when this happens, Pico returns error: "Access forbidden" and the text "You don't have access to this private website. Maybe the share was deleted or has expired?"

If not a redirect to login, perhaps the error message needs to be improved to say: "Access forbidden" and the text "You don't have access to this private website. Please login first."

**Comment by PhrozenByte** [comment]
The "Back to Nextcloud" button should redirect you to the login page, which should redirect you back to the website after a successful login.

**Comment by nooblag** [comment]
Hi there, thank you, yes I see that. I'm talking about improving either the error message (i.e. don't tell them that the share has been deleted or has expired" because that is incorrect, but rather tell them that they need to login first).

Or better yet, automatically redirect them to the login page so the behaviour is consistent with other Nextcloud apps.

For example, opening a shared doc in OnlyOffice without being logged in will redirect the user to login which I think is the desired behaviour (less clicks, improves workflow, does not show a confusing error message).

**Comment by PhrozenByte** [comment]
Ah, ic. Yeah, this is probably a good idea. Just implemented this in  9ee1d2a . Thank you for your suggestion! :+1:

**Comment by nooblag** [comment]
Okay great, thanks for taking it on board! Looking forward to it being in the next update ;)
