### ISSUE TITLE
This website is hosted on a non-local storage and thus could not be accessed.

### ISSUE THREAD

**Issue by sgofferj** [nextcloud/cms_pico#175]
NC 20.0.10 on docker
Pico CMS 1.0.15
Server side encryption: enabled / default encryption module
Encrypt the home storage: No - Double checked that web directory is not encrypted
Pico CMS web directory: /web (i.e. on the home storage)
Home storage: Docker bind mount, i.e. not external from NC point of view
Nextcloud log: no apparent related entry. I opened a console, issued ```tail -f nextcloud.log```, tried to open Pico websites and nothing appeared in the log.
URL: https://cloud.gofferje.net/ - try the TOS and privacy policy links on the bottom.

My assumption: Pico CMS only checks if the server side encryption app is enabled but does NOT check if the web directory is actually on an encrypted volume. That would be a bug because it's a common use case to enable server side encryption and only encrypt external volumes, e.g. S3, Google Drive, etc. but not the home storage.

**Comment by PhrozenByte** [comment]
You must move the files to a "Local (unencrypted)" storage. Enable Nextcloud's external storage app. This is due to how Nextcloud implements server-side encryption.

**Comment by sgofferj** [comment]
That doesn't scale very well because it requires manually creating an external volume for every user who wants to use PicoCMS... Just to be sure, you did see the part where I wrote that only external volumes are encrypted but the home directory isn't?

**Comment by PhrozenByte** [comment]
> Just to be sure, you did see the part where I wrote that only external volumes are encrypted but the home storage isn't?

Yes. As I said: "This is due to how Nextcloud implements server-side encryption."

**Comment by sgofferj** [comment]
I see. I'll implement the workaround then. Thanks. Feel free to close if you think it can't be fixed.
