### ISSUE TITLE
Error while enabling the app

### ISSUE THREAD

**Issue by VerstreuteSeele** [nextcloud/cms_pico#176]
Found this nice app, tried to add it to my nextcloud and got the following error:
`OCP\Lock\LockedException: "files/d3103cc7f9348f7715d15d25762b62f2"("local::/media/Cynthia/::scanner::") is locked, existing lock on file: exclusive`

I dont really understand this error. "media/Cynthia" is an external drive connected to the cloud. I will try enabling it while the drive is disabled but nonetheless I would love to find a fix for this

**Comment by PhrozenByte** [comment]
Can you please provide us with the full stack trace, so we can track down where this error is coming from? Check your Nextcloud logs.
