### ISSUE TITLE
Couldn't install custom themes 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/cms_pico#177]
Hello, I found some cool theme on github [ethereal](https://github.com/BesrourMS/ethereal) and I followed the instruction on Nextcloud Pico CMS Setting; I extracted the folder inside _/var/www/html/nextcloud/data/appdata_oc3m72w7hu5k/cms_pico/themes/_. After that, I pressed **Reload Custome Theme** Button, but the theme is not showing up in the list. Any help on this, Thanks.

Am using Nextcloud Version = [21.0.2]

**Comment by PhrozenByte** [comment]
Make sure that there's a `/var/www/html/nextcloud/data/appdata_oc3m72w7hu5k/cms_pico/themes/ethereal/index.twig` (and not e.g. `ethereal/ethereal/index.twig`). Also check your file permissions and ensure that your webserver resp. PHP has access to read the themes' folder (when extracting files the extracted files often have a different owner).

**Comment by elhananjair** [comment]
> Make sure that there's a `/var/www/html/nextcloud/data/appdata_oc3m72w7hu5k/cms_pico/themes/ethereal/index.twig` (and not e.g. `ethereal/ethereal/index.twig`). Also check your file permissions and ensure that your webserver resp. PHP has access to read the themes' folder (when extracting files the extracted files often have a different owner).

Yeah you are right, Now it is showing up in the list. Thanks

**Comment by elhananjair** [comment]
@PhrozenByte hello there, am sorry to reopen this issue, I have extracted the folder and now I can see the name of the custom theme in the list, and when I access the address of my link, I just see the basic content of the theme not the whole beautiful page just like as on a demo page. Is there any procedure to follow in nextcloud? I tried to ask the question on the theme repo but that theme created a long time ago and I don't think the creator would help me on that. I just wanted my page to look like this one and just edit the contents, thats what I was expecting, please correct me if am wrong. Thanks 

![pico](https://user-images.githubusercontent.com/69236638/128226115-7a5267df-8d77-4228-9ec7-a425f951d50a.png)

**Comment by elhananjair** [comment]
@PhrozenByte hello there, am sorry to reopen this issue, I have extracted the folder and now I can see the name of the custom theme in the list, and when I access the address of my link, I just see the basic content of the theme not the whole beautiful page just like as on a demo page. Is there any procedure to follow in nextcloud? I tried to ask the question on the theme repo but that theme created a long time ago and I don't think the creator would help me on that. I just wanted my page to look like this one and just edit the contents, thats what I was expecting, please correct me if am wrong. Thanks 

![pico](https://user-images.githubusercontent.com/69236638/128226115-7a5267df-8d77-4228-9ec7-a425f951d50a.png)

**Comment by elhananjair** [comment]
> You must add a `Image` and possibly a `Social` YAML header first. See the theme's sample `index.md`
> 
> ```gfm
> ---
> Image: https://source.unsplash.com/ctAsm_deVVk/525x900
> Social:
>   http://tn.linkedin.com/in/MohamedSafouanBesrour: linkedin
>   https://www.xing.com/profile/MohamedSafouan_Besrour: xing
>   https://github.com/BesrourMS: github
> ---
> This is <strong>Ethereal</strong>, a free site template by AJ for <a href="https://html5up.net">HTML5 UP</a>. It’s fully responsive, built on HTML5 and CSS3, and released entirely for free under the Creative Commons license. Hope you dig it :)
> ```
> 
> You might wanna use the `%assets_url%` placeholder like this:
> 
> ```yaml
> Image: %assets_url%/name_of_a_image_in_your_nextclouds_assets_dir.png
> ```

Thanks for replying, Actually am new to pico CMS, my problem is how exactly I will gonna have the same looks as in demo of this theme? Changing Images, I will do that but what about the styles like the slides, the gradient background and all... how can I use that html look after I extracted the theme folder from github? Thanks again @PhrozenByte

**Comment by PhrozenByte** [comment]
I'd assume that there's an issue with loading the CSS, maybe the paths are wrong? Or files aren't accessible (did you check/fix permissions of all the theme's files?). I don't see an obvious reason in the theme's `index.twig` to cause any issues. Unfortunately we can't provide support for third-party themes. Please refer to the theme developer or, if you know a little HTML/CSS, check the theme's source code. Sorry.

**Comment by elhananjair** [comment]
> I'd assume that there's an issue with loading the CSS, maybe the paths are wrong? Or files aren't accessible (did you check/fix permissions of _all_ files? just `index.twig` isn't sufficient). I don't see an obvious reason in the theme's `index.twig` to cause any issues. Unfortunately we can't provide support for third-party themes. Please refer to the theme developer or, if you know a little HTML/CSS, check the theme's source code. Sorry.

okay thanks I don't think this about permissions, I am little bit confused with how themes work in Pico CMS in general, The theme I have downloaded contains index.html(which I got from their demo site) I really wanted to be like that, but the folder I have downloaded from github just contains basic .md file, am newbie and little bit confused how things work in here. I appreciate if there is a guide included in Pico CMS readme on how to use custom themes in Pico CMS (Nextcloud). Thanks

**Comment by PhrozenByte** [comment]
A Pico website is built using (1) Markdown files containing your website's actual contents, and (2) a theme, consisting of various Twig templates (files with `.twig` file extension) describing the website's markup (i.e. stuff like your logo, your website's navigation, a footer etc.). You must use the `ethereal` folder from https://github.com/BesrourMS/ethereal as theme - the Demo website is just a static copy of the design, not a functional Pico theme.

**Comment by elhananjair** [comment]
okay thanks @PhrozenByte I will try another one or fix this one...
