### ISSUE TITLE
Unable to create a template

### ISSUE THREAD

**Issue by storm1er** [nextcloud/cms_pico#178]
Hi,

Whatever the templates I try to add, it always fails with the same message.
There's nothing in nextcloud log, which doesn't help.

I added multiple themes without any problems but I wasn't able to add any templates.
Does anyone as a working template?

![image](https://user-images.githubusercontent.com/9821946/130075097-47011e35-908b-428a-b6bc-f823f3ea2600.png)

NC: 21.0.4

**Comment by PhrozenByte** [comment]
Your templates must contain both a `assets` and `content` folder. You can use the "Copy template" button to start from the "empty" or "sample_pico" templates to create your own template.
