### ISSUE TITLE
Error 500 on websites

### ISSUE THREAD

**Issue by johnwry** [nextcloud/cms_pico#179]
For no apparent reason I am now getting error 500 on all of my PICO websites.  Please help. Here is the error log but I'm not a developer and simple stupid has me beat.

PHP Fatal error: require\_once(): Failed opening required '/home/qucgbckx/public\_html/cloud/apps/cms\_pico/appdata\_public/plugins/VC8WjBf3cK/PicoDeprecated/PicoDeprecated.php' (include\_path='/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_Crypt\_Blowfish:/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_Date:/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_Exception:/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_Idna:/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_Imap\_Client:/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_ListHeaders:/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_Mail:/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_ManageSieve:/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_Mime:/home/qucgbckx/public\_html/cloud/apps/mail/vendor/pear-pear.horde.org/Horde\_Nls:/home/q in /home/qucgbckx/public\_html/cloud/apps/cms\_pico/lib/Service/PicoService.php on line 214

**Comment by PhrozenByte** [comment]
Did your last app update fail? Please check your Nextcloud logs.

You can fix this by running `occ maintenance:repair`.

**Comment by johnwry** [comment]
No, last update using Nextcloud ran without any errors that I could see. Everything works fine except for the PICO sites.

**Comment by johnwry** [comment]
occ: command not found

**Comment by johnwry** [comment]
I reinstalled a separate installation of nextcloud and enabled the PICO app. Works fine. So I disabled the extra apps I installed on the primary Nextcloud and I now get the following:  
  
 

![](https://user-images.githubusercontent.com/66494821/132146687-5c5a6b42-14ef-4419-8566-3e5b166496f0.png)

**Comment by johnwry** [comment]
\- Preparing app data of Pico CMS for Nextcloud  
    - Checking Pico CMS requirements …  
    - Rebuilding Pico CMS app settings …  
    - Syncing Pico CMS app data folder …  
    - ERROR: "files/11890ef8206c12f0d484f26f0c39ad25"("local::/home/qucgbckx/nextclouddata/::scanner::") is locked

**Comment by johnwry** [comment]
After enabling caching in config this fixed locking issue in Nextcloud.

**Comment by johnwry** [comment]
Forgive my ignorance. Where do I access Nextcloud logs? 
How do I run occ maintenance:repair from, terminal? 

So sorry. I’m lost here. 
I am currently hosting my Nextcloud server on Cloudamo paying what I thought would cover this kind of stuff. They have sent me to my developer. 
I seem to have been better off just hosting my own.

**Comment by PhrozenByte** [comment]
> Forgive my ignorance. Where do I access Nextcloud logs?

There's a logs section in your Nextcloud's admin settings.

> How do I run occ maintenance:repair from, terminal?

Open a terminal, navigate to Nextcloud's install directory and execute `php -f ./occ -- maintenance:repair`. Please check Nextcloud's admin manual to learn more about how to use Nextcloud's `occ` command.

> - Preparing app data of Pico CMS for Nextcloud
>     - Checking Pico CMS requirements …
>     - Rebuilding Pico CMS app settings …
>     - Syncing Pico CMS app data folder …
>     - ERROR: "files/11890ef8206c12f0d484f26f0c39ad25"("local::/home/qucgbckx/nextclouddata/::scanner::") is locked
>
> After enabling caching in config this fixed locking issue in Nextcloud.

After fixing this issue you should simply re-run `occ maintenance:repair`. If another issue occurs, fix it and re-run `occ` again.

**Comment by johnwry** [comment]
Thanks @PhrozenByte ! That solved it!
