### ISSUE TITLE
Allow links to .md files

### ISSUE THREAD

**Issue by geiseri** [nextcloud/cms_pico#18]
I am not sure if this is a PicoCMS limitation or a cms_pico limitation but I would like to have links to markdown files directly.  Right now to link to a page you need to do this: `[some page](%base_url%?somepage)` and what I would rather have is `[some page](somepage.md)` or even `[some page](somepage)`

**Comment by daita** [comment]
next release will allow some direct link:

- content/page.md is accessible via sites/my_site/page
- content/foo/index.md via sites/foo
- content/foo/bar.md via sites/foo/bar

**Comment by geiseri** [comment]
Thanks!!
