### ISSUE TITLE
tables aren't rendering

### ISSUE THREAD

**Issue by johnwry** [nextcloud/cms_pico#181]
Is there any reason why my tables in markdown aren't rendering as tables? 

Here's an example table:

| 90 a 100 puntos | A |

 |---------------------------------------------------|-----------------| 

| 80 a 89 puntos | B | 

| 70 a 79 puntos | C |

 | 60 a 69 puntos | D |

 | 0 a 59 puntos | F |

**Comment by PhrozenByte** [comment]
Are you trying to write these tables with Nextcloud's Text editor? See https://github.com/nextcloud/cms_pico#nextclouds-text-app

**Comment by johnwry** [comment]
Ok will make sure I use markdown editor. What about software like Typora??

**Comment by PhrozenByte** [comment]
If Typora (never heard of it) is an actual Markdown editor I don't see a reason why it shouldn't work. Simply try.

**Comment by PhrozenByte** [comment]
If you have issues with enabling a editor app, refer to https://github.com/icewind1991/files_markdown#behaviors
