### ISSUE TITLE
doesn't work with Nextcloud 21.04

### ISSUE THREAD

**Issue by dtxl** [nextcloud/cms_pico#182]
After upgrading to the Nextcloud version 21.04 the cms_pico app was disabled because of incompatibility.

**Comment by PhrozenByte** [comment]
We kinda need a little more info here :wink:

> Before creating a new Issue, please make sure the problem wasn’t reported yet using GitHubs search engine on both the nextcloud/cms_pico and picocms/Pico repos, as well as the search of Nextcloud Help. Please describe your issue as clear as possible and always include the version of Pico CMS for Nextcloud you’re using. Provided that you’re using custom plugins and/or themes, include a list of them too. We need information about the actual and expected behavior , the steps to reproduce the problem, and what steps you have taken to resolve the problem by yourself (i.e. your own troubleshooting).

https://github.com/nextcloud/cms_pico#getting-help

**Comment by dtxl** [comment]
right sorry. The app was disabled after the upgrading of nextcloud vanished from the installed / enabled apps. Trying to enable it gives "App cms_pico cannot be installed because appinfo file cannot be read."

**Comment by PhrozenByte** [comment]
Looks like your app installation is broken. Backup your installation first. Then remove the app and reinstall it.

**Comment by dtxl** [comment]
Thanks. I deinstalled the app, but with "Download and enable" the message remains the same.

**Comment by PhrozenByte** [comment]
Make sure the `apps/cms_pico` folder is deleted after you've removed the app. I assume that the file permissions aren't right and PHP doesn't have access to the folder.

**Comment by dtxl** [comment]
Deleting this folder solved the problem. Thank you.
