### ISSUE TITLE
Poor Performance on Some Sites

### ISSUE THREAD

**Issue by paulb-opusvl** [nextcloud/cms_pico#183]
We have a couple of sites hosted in Nextcloud 19 with cms_pico. Two of them are unbearable to use, despite one of them only having one page.

What we are seeing is a delay of 10 seconds before the page is handed out to the browser. I've established that the issue is within Nextcloud/Pico but don't know how to debug it further.

The Nextcloud instance is a docker build and from inside the container I see the delay using curl, eg.

```shell
$ time curl -H 'Host: mysite' localhost -vL
* Expire in 0 ms for 6 (transfer 0x555c49643e20)
...
</body>
</html>
* Connection #1 to host mysite left intact

real	0m14.629s
user	0m0.012s
sys	0m0.016s
```

Yet on the same system for another site, I get far better results:

```shell
* Connection #1 to host mygoodsite left intact
...

real	0m0.857s
user	0m0.016s
sys	0m0.012s
```

What I am seeing in the Nextcloud log are lots of:

```json
{
    "reqId": "JJfbXgA66QOrB5soAXMv",
    "level": 0,
    "time": "2021-10-01T07:20:54+00:00",
    "remoteAddr": "X.X.X.X",
    "user": "--",
    "app": "workflowengine",
    "method": "GET",
    "url": "/index.php/apps/cms_pico/pico/mysite/",
    "message": "Flow activation: rules were requested for operation Block access to a file",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.83 Safari/537.36",
    "version": "19.0.13.1"
}
```

But I'm not seeing anything in the workflow that would block it. I've even disabled all the workflow apps and still I see the delay.

Grateful for any suggestions.

**Comment by PhrozenByte** [comment]
Please disable the workflowengine app temporarily and try again. Does the issue persist? Are there any custom Pico plugins or themes involved? If yes, disable them one after another until either the issue no longer persists (you found the plugin/theme causing the issue then), or all custom plugins/themes are disabled.

**Comment by paulb-opusvl** [comment]
I'm going to close this because after recreating the site and moving the content we found that it contained 500+ markdown files!

It seems to suggest that at the point the nav is generated, it scans all md files to figure out what to do. When it hit the folder containing all these md's it crawled.

We need to think of a way to handle this.

Thanks for your response though.

**Comment by matt-horwood-mayden** [comment]
Just had a very similar issue with my nextcloud pico install, I have moved my nextcloud to a new server on a dedicated host from OVH fronted by PFSense.

It turns out that the `pico_proxy` request from nginx was not happy talking to the external IP of my PFSense, had to add an internal DNS entry for the internal IP of the nginx server. now all happy.
