### ISSUE TITLE
Plugin looks correctly installed, but ToC doesn't display

### ISSUE THREAD

**Issue by jlgarnier** [nextcloud/cms_pico#184]
Hi all!

Here's a bit of context:

- I'm using a dockerized instance of Nextcloud.
- Due to special disks configuration, both application and data are hosted into /home:
  - /home/nextcloud/html is /var/www/html, while /home/nextcloud/data is /var/www/html/data
- Pico CMS plugin is installed into html/custom_apps/cms_pico. It's active and running, test pico sites have been correctly created.
- As required by the documentation, the TableOfContents plugin has been copied into /home/nextcloud/data/appdata_xxxxx/cms_pico: Pico CMS correctly finds and activates the plugin (Custom extensions).
- I've modified an example pico site and included the following lines into the index.md file:
```
---
Title: The Admin News
Description: information about the latest updates applied to the application and environment
---

# The Admin News

<toc min-level="2" max-level="2" heading="Table of Contents" />

## What's new with Nextcloud?

This (micro)website is your resources one-stop-shop: **tips and tricks**, update news, main tickets followup, you'll find plenty of information from your beloved Admin here!

## How to...?

Users who are new to Nextcloud may be impressed by its power, but do you know you can do much (work) with less (effort)?

| How to? | Read how |
| --- | --- |
| Create my own blog or *knowledge base* | Ask your admin if you don't find the Pico application in your private menu and create a Pico website |
| Open a ticket | Just mail your issue (with context) to your admin |

```

The file is properly displayed but the `<toc />` tag is totally ignored and not rendered by Pico CMS. It's neither displayed as raw text, so seems to be processed and silently 'swallowed' by the CMS engine.

Is there anything wrong in the configuration here above? Could the peculiar folders structure cause such an issue? Any clue to troubleshoot this issue?

Thanks in advance for any help!

**Comment by PhrozenByte** [comment]
Unfortunately plugins using custom HTML tags (like `<toc />`) aren't supported by Pico CMS for Nextcloud for security reasons. All contents are fed into HTMLPurifier to remove potentially malicious contents (like JavaScript). To do so, HTMLPurifier removes everything it doesn't understand - including the `<toc />` element.

You might wanna ask the plugin developer to update the plugin to either use another marker instead (e.g. `[toc]`), or, even better, allow theme developers to add TOCs to the theme instead (a TOC semantically is no part of a website's contents).

**Comment by jlgarnier** [comment]
Hi!

The developer has updated his plugin (actually a plugin of a plugin) to use a [toc] tag but this tag seems to be overlooked by the HTML engine. Could this be related to HTMLPurifier too and is there any way to "protect" this tag from being wiped?

Thanks in advance for any help!

**Comment by PhrozenByte** [comment]
I assume it is working now? https://github.com/iridescent-dev/pico-toc-plugin/issues/6#issuecomment-968759737

**Comment by jlgarnier** [comment]
Yes, it works fine now and you may close this case!
Thanks again for your support!
