### ISSUE TITLE
The file and directory structure of this website appears to be broken and thus could not be accessed.

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/cms_pico#190]
**Hello guys, am using pico cms version v1.0.17 with Nextcloud 23**

This is what I have done so far; I have downloaded this theme from (https://github.com/BesrourMS/ethereal) and extracted it inside "/nextcloud/data/appdata_oc3m72w7hu5k/cms_pico/themes/", here is index.twig file I have used [index.twig](https://mega.nz/file/wQI0iZoL#qCGatpq2l9hCi96cIjLt4-slQIZnSaIHVFVkT839pWs)
After that I have downloaded [this](https://html5up.net/ethereal) demo HTML page and extracted inside a path I specified while creating a website using pico cms setting in nextcloud. 
Finally when I tried to access the website am seeing this error. Can someone please support me on this, thanks 

 
![image](https://user-images.githubusercontent.com/69236638/150351112-c1e9f0cb-e17f-4cea-bb29-4d1fe5a6bc47.png)

**Comment by PhrozenByte** [comment]
All website source directories (i.e. the directory in your Nextcloud) require a `assets` and a `content` directory. Simply use the built-in `sample_pico` template to start creating your own Markdown contents with your custom theme.

**Comment by PhrozenByte** [comment]
Please check out Pico's [About](https://picocms.org/about/) page and the [Docs](https://picocms.org/docs/). Contents are written in Markdown, themes use Twig, HTML and CSS. The Ethereal theme was ported to Pico by BesrourMS before, see https://github.com/BesrourMS/ethereal.
