### ISSUE TITLE
Cannot install - no app selection menu on NextCloud

### ISSUE THREAD

**Issue by pd-giz-dave** [nextcloud/cms_pico#193]
I installed Nextcloud version 23 via Cloudron on a Digital Ocean droplet - fine, I can log-in to Nextcloud. But I specifically wanted the Pico CMS app and I cannot install any apps into Nextcloud because there is no App menu. Attached is a screenshot of the Nextcloud instance - there is no means to install an app. What do I need to do?
![Screenshot from 2022-02-18 13-00-02](https://user-images.githubusercontent.com/17320192/154687536-6e433c6c-f529-4414-9367-8c1764f0dd33.png)
.

**Comment by PhrozenByte** [comment]
Please refer to the app's app store description and our `README.md`:

> You want to learn more about Pico CMS for Nextcloud? Easy! Just download and enable the app from [Nextcloud's App Store](https://apps.nextcloud.com/apps/cms_pico) and navigate to Nextcloud's settings page. As an admin you'll find two "Pico CMS" sections in your Nextcloud settings - one below "Personal", another below "Administration". The latter allows you to add custom themes, plugins and templates to Pico, as well as tweaking some advanced settings. The "Pico CMS" section below "Personal" exists for all Nextcloud users and allows one to create personal websites. Simply create your first personal website and choose "sample_pico" as website template. Pico's sample contents will explain all you need to know… wave
