### ISSUE TITLE
Trying to us Pico::getFormParameter() but got HTTP error 405 Method not Allowed

### ISSUE THREAD

**Issue by MarkPartlett** [nextcloud/cms_pico#194]
Hi,

I am trying to use a submit button to do a POST and use Pico::getFormParameter() to read the POST variables. I only get a HTTP error 405 Method is not allowed. 

Is this a 'Pico CMS on Nextcloud' issue? 

Thanks for GREAT product.
Mark

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud registers no route for `POST` requests right now, so this is indeed not possible, but adding it is no big deal. I'll add this to v1.1 later (currently in beta).

**Comment by MarkPartlett** [comment]
When is the next version of v1.1 being released? I can verify the update works for HTTP POSTs! :)

Thank you!
