### ISSUE TITLE
Website cant opened

### ISSUE THREAD

**Issue by PadseGaming** [nextcloud/cms_pico#199]
Hi, i've installed Pico CMS and started building a website through the form. After complete the website building, i've tryed the link "open Website" but i still land on the dashboard page. 

I've tryed to deactivate the Nextcloud Text App because i read that this is incompatible and installed Markdown editor. I've reinstalled a new Website through the form and still land on the dashboard if i try to open the Website. 

What i am doing wrong? Is there something i missed to configure? I cant find help in the users documentatioon and also nothing in issues section.

**Comment by PhrozenByte** [comment]
What's the website's ID you're trying to access? Try navigating directly to `https://example.comn/extcloud/index.php/apps/cms_pico/pico/<website ID>/`.

Make sure you didn't configure "short URLs" in Pico's admin settings unless you didn't configure your webserver as described there.

Check your webserver's error log, PHP's error log as well as Nextcloud's logs.

Try re-installing the `cms_pico` app (remove the app via the admin interface, then also remove the `apps/cms_pico` directory via FTP, and install the app again) and create a new website.

Try running `occ maintenance:repair` via shell.

**Comment by PadseGaming** [comment]
lot of thanks PhrozenByte. U've kicked me in the right direction and i found that i have'nt righly configured Pico in the Admin section. I now will go configure my Apache correctly. Ur navigation URI works fine for the moment. ;)
