### ISSUE TITLE
Creating a site on encryption-enabled cloud doesn't work

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/cms_pico#2]
When creating a page on master of the app and Nextcloud and then accessing it at `https://10.211.55.7/stable9/index.php/apps/cms_pico/pico/my_site` all I get is:

> "Invalid content directory \"\/tmp\/oc_tmp_xOamFW\/content-sample\/\""

<img width="796" alt="screen shot 2017-09-18 at 15 35 49" src="https://user-images.githubusercontent.com/878997/30544533-108daf28-9c87-11e7-91a6-2de8342726cd.png">
<img width="941" alt="screen shot 2017-09-18 at 15 36 14" src="https://user-images.githubusercontent.com/878997/30544542-1ed0460e-9c87-11e7-8af5-d06b381b169f.png">

**Comment by LukasReschke** [comment]
This seems to be caused because I have encryption enabled. It would probably make sense to use the same workaround that Collabora uses https://github.com/nextcloud/richdocuments/pull/78/files

**Comment by weipah** [comment]
I also have the default server-side encryption enabled for the user and get error:

> cms_pico does not support encrypted filesystem

That is quite the show stopper I think.

Is there any workaround despite creating a seperate user without encrption enabled?

**Comment by KopfKrieg** [comment]
> Is there any workaround despite creating a seperate user without encrption enabled?

This is possible? I thought enabling the encryption is global, for all users?

**Comment by weipah** [comment]
@KopfKrieg I checked. You're right, as it seems it's not possible to disable user data encryption for single users. I guess I was misslead by the German translation in the interface. Bummer.

**Comment by PhrozenByte** [comment]
This has been fixed resp. circumvented in `v1.0.2`. You can now create a "Local (unencrypted)" external storage on your Nextcloud and move all your website's source folders to this unencrypted local directory, allowing Pico CMS for Nextcloud to access those files.

**Comment by ludogre** [comment]
Hi!
> This has been fixed resp. circumvented in `v1.0.2`. You can now create a "Local (unencrypted)" external storage on your Nextcloud and move all your website's source folders to this unencrypted local directory, allowing Pico CMS for Nextcloud to access those files.

Very interesting. How can we create an unencrypted folder?

**Comment by KopfKrieg** [comment]
> How can we create an unencrypted folder?

You need to download and activate the "External Storage" application. In your Nextcloud's settings you'll then be able to create a new, unencrypted local storage.
