### ISSUE TITLE
Opening pico_cms site gives internal server error

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/cms_pico#200]
Nextcloud 24
App Version 1.0.19

All pico sites do not work anymore and result in internal server error (this is also true for the example site of pico_cms).

**Comment by PhrozenByte** [comment]
https://github.com/nextcloud/cms_pico#getting-help

> Before creating a new Issue, please make sure the problem wasn’t reported yet using GitHubs search engine on both the [nextcloud/cms_pico](https://github.com/nextcloud/cms_pico/search?type=Issues) and [picocms/Pico](https://github.com/picocms/Pico/search?type=Issues) repos, as well as the [search of Nextcloud Help](https://help.nextcloud.com/search). Please describe your issue as clear as possible and always include the exact error message (if any) as well as all related messages in Nextcloud's logs. Also include the exact Nextcloud version and the version of Pico CMS for Nextcloud you’re using. Provided that you’re using custom plugins and/or themes, include a list of them too. We need information about the actual and expected behavior , the steps to reproduce the problem, and what steps you have taken to resolve the problem by yourself (i.e. your own troubleshooting).

**Comment by sirdrakeistda** [comment]
{"reqId":"YnJEs5i70xCkyNCN49EdasugE","level":2,"time":"2022-05-04T09:17:39+00:00","remoteAddr":"213.1127.123.70","user":"--","app":"core","method":"GET","url":"/","message":"Trusted domain error. \"213.226.123.30\" tried to access}

**Comment by PhrozenByte** [comment]
> Trusted domain error. "213.226.123.30" tried to access

Looks like this isn't related to Pico CMS for Nextcloud.

**Comment by sirdrakeistda** [comment]
The rest of Nextcloud works fine (also in browser), so I'm wondering what could cause this issue just for pico_cms.

**Comment by PhrozenByte** [comment]
Try running `occ maintenance:repair` via shell.

**Comment by sirdrakeistda** [comment]
Thanks this fixed the issue for me.
