### ISSUE TITLE
pico requires apps/pico_cms to be writeable

### ISSUE THREAD

**Issue by arnottcr** [nextcloud/cms_pico#201]
My installation of nextcloud, on nixos, manages app code in an immutable way, disallowing them from changing or mutating `~nextcloud/apps/cms_pico/`. This works fine for all the other apps we have, since they use `~nextcloud/data/appdata_.../cms_pico` for configuration data. Unfortunately cms_pico writes themes and templates to `~nextcloud/apps/cms_pico/appdata_public/{templates,plugins}`.

Since it looks like we fork pico to make changes and integrate with nextcloud, could we have pico use `~nextcloud/data/appdata_.../cms_pico` as `~nextcloud/apps/cms_pico/appdata_public/{templates,plugins}`?

If not, is there a simple way to have pico point to an external directory for `appdata_public`? I am looking to do this via configuration, not code changes, as I would rather not fork this project.

**Comment by PhrozenByte** [comment]
> Since it looks like we fork pico to make changes and integrate with nextcloud, could we have pico use `~nextcloud/data/appdata_.../cms_pico` as `~nextcloud/apps/cms_pico/appdata_public/{templates,plugins}`?

No, because Nextcloud's data directory isn't accessible by browser for obvious reasons. The `appdata_public` is necessary to publish theme assets like CSS, JavaScript, etc.

> If not, is there a simple way to have pico point to an external directory for `appdata_public`? I am looking to do this via configuration, not code changes, as I would rather not fork this project.

You might wanna use symbolic links. However, don't symlink it to Nextcloud's `data` directory, as this might impose security issues, but any other (writable) directory.
