### ISSUE TITLE
Defect: Fails to activate initially (see log below)

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/cms_pico#205]
NC Version:24.0.1
PICO CMS App Version:  1.0.19

Errors:

[index] Fehler: Exception: Illegal offset type in file '/var/www/nextcloud/apps/cms_pico/lib/Migration/Version010000From000908.php' line 107 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1023
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

POST /nextcloud/index.php/settings/apps/enable
from ...

[PHP] Fehler: Error: Array to string conversion at /var/www/nextcloud/apps/cms_pico/lib/Migration/MigrationTrait.php#65 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError()
 1. /var/www/nextcloud/apps/cms_pico/lib/Migration/MigrationTrait.php line 65
    sprintf()
 2. /var/www/nextcloud/apps/cms_pico/lib/Migration/Version010000From000908.php line 105
    OCA\CMSPico\Migration\Version010000From000908->logInfo()
 3. /var/www/nextcloud/apps/cms_pico/lib/Migration/Version010000From000908.php line 84
    OCA\CMSPico\Migration\Version010000From000908->migrateCustomTemplates()
 4. /var/www/nextcloud/lib/private/DB/MigrationService.php line 547
    OCA\CMSPico\Migration\Version010000From000908->postSchemaChange()
 5. /var/www/nextcloud/lib/private/DB/MigrationService.php line 425
    OC\DB\MigrationService->executeStep()
 6. /var/www/nextcloud/lib/private/Installer.php line 154
    OC\DB\MigrationService->migrate()
 7. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 451
    OC\Installer->installApp()
 8. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AppSettingsController->enableApps()
 9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
10. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
11. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
12. /var/www/nextcloud/lib/base.php line 1023
    OC\Route\Router->match()
13. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

POST /nextcloud/index.php/settings/apps/enable
from ...

**Comment by PhrozenByte** [comment]
That's weird, because this config value shouldn't exist if the app wasn't installed before. Check your Nextcloud database manually (e.g. using phpMyAdmin): Table `oc_appconfig`, `appid` is `cms_pico`, `configkey` is `custom_templates`; the value we need is in the `configvalue` column.

**Comment by MrLoverLoverMMMM** [comment]
I deleted all config related to pico_cms manually from the db and it works now ;)
thanks
