### ISSUE TITLE
Limit pageaccess to NC group

### ISSUE THREAD

**Issue by qroac** [nextcloud/cms_pico#207]
I'd like to use this app for our internal documentation folder.
Thus it should not be public but it should be accessible by members of specific nextcloud groups.
I couldn't find information on this in the readme or other issues.

Is it currently possible to set access to a page not 'private' or 'public' but to authenticated users or specific groups?
Is it planned to add a feature like that?

**Comment by PhrozenByte** [comment]
For Pico CMS for Nextcloud v1.0: Set the website to private and share the website's source folder with the group.
For Pico CMS for Nextcloud v2.0 (current `master` branch, latest beta is v1.1.0-beta.1): Use the distinct "Share with groups" feature.

**Comment by qroac** [comment]
Well, that's something to look forward to :)
Looking forward to this in the appstore.
I think I'll already give it a try from master branch

Thank you for your work and support
