### ISSUE TITLE
Unable to change date_format

### ISSUE THREAD

**Issue by sm8ps** [nextcloud/cms_pico#208]
Is it possible to override the default value of `date_format`? Adding a line like `date_format: "%Y-%m-%d"` to `/var/www/nextcloud/apps/cms_pico/appdata_public/themes/*/THEME/pico-theme.yml` does not seem to have any effect.

Is that even the correct place? I have also changed `/var/nextcloud_data/appdata_*/cms_pico/themes/THEME` to no avail. This is with Pico 1.0.19 on NC 24.0.4.

**Comment by PhrozenByte** [comment]
You can change the default `date_format` in `/var/nextcloud_data/appdata_*/cms_pico/config/config.yml` (check `config.yml.template` for all options available)

**Comment by sm8ps** [comment]
Thanks a lot @PhrozenByte for your quick answer! It is working as expected.

Answering my second question after studying (and finally understanding) the docs on the admin page of Pico CMS, I understood that changes should be made in `/var/nextcloud_data/appdata_*/cms_pico/themes/THEME/` and they get transferred to `/var/www/nextcloud/apps/cms_pico/appdata_public/themes/*/THEME/pico-theme.yml` by refreshing the theme on the admin page.

"Stupdily simple" sounds deceptively inviting to simple-minded people like me. (:

**Comment by mayamcdougall** [comment]
Just for the record, `pico-theme.yml` is something entirely different.

It's a config file for a Theme Developer to use.  It can be used for development things like registering metadata headers for your theme, storing variables, and defining theme-specific config settings (which users can then override in their own `config.yml` file).

It's not a place for your personal settings (which live in `config.yml`).

(Sorry to butt in, just wanted to make sure you weren't accidentally getting the wrong take away from this. 😅)

Also, sometimes I wonder if the Nextcloud app can *really* be called "Stupdily simple", as it's a fair bit more complicated to work with than standard Pico. 🤔

**Comment by sm8ps** [comment]
Thanks for the clarifications, @mayamcdougall! In fact, I am still trying to get a concise picture of the inner workings of Pico on Nextcloud and also making sense of them. My plans for world domination with it are growing very slowly, indeed.
