### ISSUE TITLE
Compat NC11 - error application activation

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/cms_pico#21]
Hello, 

I am on nextcloud 11.0.5.1, if i change  in appinfo the file info.xml the section:
	dependencies
		nextcloud min-version="11" max-version="13"
	dependencies
I have a error when i try to activate this application:
Erreur lors de l'activation de l'application - error application activation

How can i resolv this error, please ?

In my nextcloud log i see this error line:
"PHP","message":"Interface 'OCP\\Settings\\IIconSection' not found at \/var\/www\/nextcloud\/apps\/cms_pico\/lib\/Settings\/AdminSection.php#34"

I have found this:
https://fossies.org/diffs/nextcloud/11.0.3_vs_12.0.0/settings/Controller/AdminSettingsController.php-diff.html

iiconSection not exist in 11.0.5.1...

**Comment by daita** [comment]
After further review, cms_pico needs at least 12.0.2
