### ISSUE TITLE
%base_url% placeholder

### ISSUE THREAD

**Issue by scubajeff** [nextcloud/cms_pico#212]
The %base_url% placeholder is being replaced with a url without the host segment, is this related to the wrong config of url rewriting of Apache?

**Comment by PhrozenByte** [comment]
This is expected behaviour in Pico CMS for Nextcloud, just as with Nextcloud. Browsers use the current host as default.

**Comment by scubajeff** [comment]
I see. So I have to find some other ways when trying to share the page link out. Thank you very much.
