### ISSUE TITLE
REQ: limit Pico to groups!!!!!!

### ISSUE THREAD

**Issue by punkyard** [nextcloud/cms_pico#214]
every user can create a web site, or access a menu to do so
it's confusing for the users not involve in this task

please, add the limit to group in the App list :D

**Comment by PhrozenByte** [comment]
This feature exists already.

By the way: You should add a few more exclamation marks.

**Comment by punkyard** [comment]
ok, cool !!!! usually Limits are set in the App list, but not for pico !!!!!!!!!
it's in the preferences !!!!!!!!!!!! ok 😘

![Capture d’écran 2022-11-08 à 18 56 54](https://user-images.githubusercontent.com/59349105/200640227-4711fe1a-ecbb-40b9-8fd2-00c1badc308f.png)
