### ISSUE TITLE
Internal server error in NC24

### ISSUE THREAD

**Issue by kugiigi** [nextcloud/cms_pico#215]
### Description
After upgrading from NC 23 to NC 24, I'm getting an internal server error when accessing my site.
During the upgrade, PHP was also upgraded to PHP 8.

### Additional Information
There's also an error adding some themes i.e. freelancer
Upon investigation, I was able to add the theme by not including the file `pico-theme.yml` in the folder.
I was also able to fix the internal server error by removing all line breaks in all content properties. Sadly, this means no multiple paragraphs like in the about section which I do.

There are YAML syntax like starting the value with a pipe `|` + line break to add multi paragraph texts. This however causes the internal server error.

**Comment by PhrozenByte** [comment]
As per https://github.com/mayamcdougall/freelancer-pico/issues/10 I'd say this is indeed a duplicate of #121.
