### ISSUE TITLE
Unable to enable cms_pico on Nextcloud 25.0.1

### ISSUE THREAD

**Issue by Mythotical** [nextcloud/cms_pico#219]
I have checked the logging page and this is the error:
`{"reqId":"Y27cI3nozAfwHPIJSxr02QAA0V8","level":3,"time":"2022-11-11T23:34:59+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"Cupara","app":"index","method":"POST","url":"/settings/apps/enable","message":"OC\\Files\\Utils\\Scanner::__construct(): Argument #4 ($logger) must be of type Psr\\Log\\LoggerInterface, OC\\Log given, called in /home/admin/domains/serenitydev.xyz/public_html/apps/cms_pico/lib/Files/StorageFolder.php on line 204 in file '/home/admin/domains/serenitydev.xyz/public_html/lib/private/Files/Utils/Scanner.php' line 95","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36","version":"25.0.1.1","exception":{"Exception":"Exception","Message":"OC\\Files\\Utils\\Scanner::__construct(): Argument #4 ($logger) must be of type Psr\\Log\\LoggerInterface, OC\\Log given, called in /home/admin/domains/serenitydev.xyz/public_html/apps/cms_pico/lib/Files/StorageFolder.php on line 204 in file '/home/admin/domains/serenitydev.xyz/public_html/lib/private/Files/Utils/Scanner.php' line 95","Code":0,"Trace":[{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"OC\\Files\\Utils\\Scanner::__construct(): Argument #4 ($logger) must be of type Psr\\Log\\LoggerInterface, OC\\Log given, called in /home/admin/domains/serenitydev.xyz/public_html/apps/cms_pico/lib/Files/StorageFolder.php on line 204","Code":0,"Trace":[{"file":"/home/admin/domains/serenitydev.xyz/public_html/apps/cms_pico/lib/Files/StorageFolder.php","line":204,"function":"__construct","class":"OC\\Files\\Utils\\Scanner","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/apps/cms_pico/lib/Service/FileService.php","line":186,"function":"sync","class":"OCA\\CMSPico\\Files\\StorageFolder","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/apps/cms_pico/lib/Migration/AppDataRepairStep.php","line":170,"function":"syncAppDataFolder","class":"OCA\\CMSPico\\Service\\FileService","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/apps/cms_pico/lib/Migration/AppDataRepairStep.php","line":140,"function":"syncAppDataFolder","class":"OCA\\CMSPico\\Migration\\AppDataRepairStep","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/Repair.php","line":126,"function":"run","class":"OCA\\CMSPico\\Migration\\AppDataRepairStep","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/legacy/OC_App.php","line":1064,"function":"run","class":"OC\\Repair","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/Installer.php","line":164,"function":"executeRepairSteps","class":"OC_App","type":"::"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/home/admin/domains/serenitydev.xyz/public_html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/admin/domains/serenitydev.xyz/public_html/lib/private/Files/Utils/Scanner.php","Line":95},"CustomMessage":"--"},"id":"636edc31b3734"}`

**Comment by FrenchHope** [comment]
+1

**Comment by PhrozenByte** [comment]
Can't reproduce this issue. Did you upgrade to `cms_pico` v1.0.21?
