### ISSUE TITLE
Readme blogging theme/template clarification

### ISSUE THREAD

**Issue by hippi-viking** [nextcloud/cms_pico#221]
Please clarify in the [default readme](https://github.com/nextcloud/cms_pico/blob/master/appdata/templates/sample_pico/content/index.md) which 'themes' directory to use in the 'Blogging' section:

- nextcloud_data/appdata_XYZ/cms_pico/themes
- nextcloud/apps/cms_pico/appdata/themes
- nextcloud/apps/cms_pico/appdata_public/themes/(XYZ)

Should the new .twig file be straight in the themes directory or should the default theme (directory) be cloned and renamed / and / or just the index.twig file renamed?

**Comment by PhrozenByte** [comment]
Please check the theme admin page:

![](https://github.com/nextcloud/cms_pico/blob/master/screenshots/custom_themes.png?raw=true)

You copy your base theme to create a new custom theme and edit the files in `nextcloud_data/appdata_XYZ/cms_pico/themes`, then hit the "Sync theme" button.

**Comment by hippi-viking** [comment]
@PhrozenByte Ah, thank you, i missed that. I was only reading the sample content page where i did not find this info. Would it make sense to put this info there as well? I know it probably would not be able to display the whole path correctly but a generalised one like `nextcloud_data/appdata_XYZ/cms_pico/themes` would help people not reading the theme admin page... (sorry) :)
