### ISSUE TITLE
The wrong 404 page is displayed

### ISSUE THREAD

**Issue by seabokas** [nextcloud/cms_pico#224]
Hi, 

by the way, fantastic plugin.

Despite the `404.md` in the `content` directory, the NextCloud 404 page is displayed when a url is called that does not exist.

https://sub.myurl.com/sites/newsite/ 
Works fine.

https://sun.myurl.com/sites/nonexistingsite/ 
Shows the standard NC 404 page.

NC 25.0.1
Pico CMS 1.0.21
PHP 8.1.12

**Comment by PhrozenByte** [comment]
This is expected behaviour, because since you didn't request a site (each site is a separate Pico instance), Pico can't know which `404.md` to display.
