### ISSUE TITLE
Shows a 404 page on the base link due to url duplication (using .htaccess file only)

### ISSUE THREAD

**Issue by poVoq** [nextcloud/cms_pico#23]
Just updated to version 0.95 and now there is an issue with the redirection. I am using the mod rewrite.

When I go to
https://myurl.com/sites/newsite/
it gives me the pico cms 404 page because it redirects to:
...index.php/apps/cms_pico/pico/newsite/newsite

Probably the same cause as this:
https://github.com/nextcloud/cms_pico/issues/22

**Comment by daita** [comment]
I cannot reproduce the bug, can you provide more details about the lines you added to the Apache configuration

**Comment by poVoq** [comment]
As by the instructions:
RewriteRule /sites/(.*) https://mysite.com/nextcloud/index.php/apps/cms_pico/pico/$1 [QSA,L]

**Comment by daita** [comment]
I made some test with a webroot like your configuration 'mysite.com/nextcloud/index.php' and fixed some bugs from the list of the website in the personal settings.

But I still were not able to reproduce this bug. Could you check again the configuration of your apache from the begining ?

**Comment by poVoq** [comment]
I have honestly no idea what else to change and it runs on a shared host.
You have have a look at the webconsole output on this life page:
https://watsan.eu/sites/testing

**Comment by daita** [comment]
does it means that you don't have full control over apache configuration ?

**Comment by poVoq** [comment]
Yes only .htaccess editing. But as I said, this problem did not occur with version 0.94 and I did not change the .htaccess file meanwhile.

**Comment by scar86** [comment]
Hello
I may have a similar issue but with 0.9.6, it is the first time I install the app on my site
My site is not on the root directory of apache, it is instead on /nextcloud like https://mysite.com/nextcloud
If I create a new site using cms_pico it tell me that my address should be https://mysite.com/sites/my_site that is wrong since it is missing the /nextcloud part on the address, I also tried to access it like https://mysite.com/nextcloud/sites/my_site with no luck, both links only trough the 404 not fund apache site

I have fully control on the apache server in case something is required to debug the problem

Thanks !

**Comment by poVoq** [comment]
No this is unrelated. You just need to setup the .htaccess file accordingly.

**Comment by daita** [comment]
@poVoq : the strange thing is that it looks like an issue with the rewrite from your apache configuration, and not an issue with the app itself.

@scar86 : @poVoq is right, it seems that you haven't configured your Apache

**Comment by scar86** [comment]
Thanks a lot guys !, I didn't even know that I need to configure Apache, it is working now

**Comment by poVoq** [comment]
With 0.97 this still happens.

Somehow the "my_site" appendix is added again as a parameter or so.

So if I go to https://mydomain/sites/my_site
I end up at https://mydomain/nextcloud/index.php/apps/cms_pico/pico/my_site/my_site
Which is of course a 404.

But for example if I go to:
https://mydomain/sites/my_site/
I end up at https://mydomain/nextcloud/index.php/apps/cms_pico/pico/my_site//my_site

And if I try to go to:
https://mydomain/sites/my_site/index
I end up at https://mydomain/nextcloud/index.php/apps/cms_pico/pico/my_site/index/my_site/index

I really can't see where my .htaccess file might be causing this, so I am really at a loss.

**Comment by poVoq** [comment]
Ok, what seems to have fixed it was to create a dummy directory called "sites" in my web-root.

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Can you please check whether your issue persists with Pico CMS for Nextcloud v1.0.0? I couldn't reproduce it. If your issue persists, please open a new Issue here on GitHub.
