### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by michelwend** [nextcloud/cms_pico#24]
Hello,
You present the configuration for apache. But what should we do for nginx?
Thank you

**Comment by 11111000000** [comment]
+1 nextcoud / pico

**Comment by ewilly** [comment]
Hello,
as a start perhaps somethings like this
`location /sites/ {
##MOD_REWRITE
  #rewrite /sites/(.*) https://$server_name/nextcloud/index.php/apps/cms_pico/pico/$1 redirect;

##MOD_PROXY
  rewrite /sites/(.*) /nextcloud/index.php/apps/cms_pico/pico/$1 break;
  proxy_redirect off;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Server $host;
  proxy_pass https://example.com/;
}`

**Comment by uhe-on-github** [comment]
+1 nginx / nextcloud / pico

**Comment by Dasoren** [comment]
Has anyone figured this out yet? maybe has an example?

**Comment by Schmuuu** [comment]
I used the example from @ewilly  above and it is working fine for me:
```
location /sites/ {
        rewrite /sites/(.*) /apps/cms_pico/pico/$1 break;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_pass https://sub.domain.tld/;
    }
```
The only difference is, that it is not
```
    rewrite /sites/(.*) /nextcloud/index.php/apps/cms_pico/pico/$1 break;
```
but
``` 
    rewrite /sites/(.*) /apps/cms_pico/pico/$1 break;
```
(so without /nextcloud/index.php/ because I'm using shortened URLs).

**Comment by rollanders** [comment]
I could not find out in NC13. This is the default instructiuon

Using MOD_PROXY: 
ProxyPass /sites/ http://cloud.mydomain.com/index.php/apps/cms_pico/pico/ 
ProxyPassReverse /sites/ http://cloud.mydomain.com/index.php/apps/cms_pico/pico/

Using MOD_REWRITE:
RewriteEngine On 
RewriteRule /sites/(.*) http://cloud.mydomain.com/index.php/apps/cms_pico/pico/$1 [QSA,L]

Using MOD_REWRITE and  MOD_PROXY:
RewriteEngine On 
RewriteRule /sites/(.*) http://cloud.mydomain.com/index.php/apps/cms_pico/pico/$1 [P]

When looking in the folder tree the mappstructure is different from the above.  

I look for a folder pico (with minuscle p) and find this 
/var/lib/docker/volumes/dockeronlyofficeowncloud_app_data/_data/custom_apps/cms_pico/vendor/picocms/pico

Looking for Pico (majuscle P) gives /var/lib/docker/volumes/dockeronlyofficeowncloud_app_data/_data/custom_apps/cms_pico/Pico

Any suggestion about the rewrite rule for nginx?

**Comment by Bellusterra** [comment]
You can Try This:
[https://www.c-rieger.de/nextcloud-meets-picocms/](url)

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Pico CMS for Nextcloud v1.0.0 also includes configuration examples for nginx.
