### ISSUE TITLE
cms_pico for Nextcloud plugins directory not working

### ISSUE THREAD

**Issue by toneji** [nextcloud/cms_pico#241]
I am using Nextcloud Hub 5 27.0.2.
I installed Pico CMS from the "Apps" menu. The installation is successful without problems; I can create web pages using Pico and rewrite the content using Markdown. The following versions are installed.

```
Pico CMS for Nextcloud 1.0.21
Pico 2.1.4
```
My plugins directory is as follows:
`/var/www/nextcloud/data/appdata_ocb07hx8s3dn/cms_pico/plugins/`

I git-cloned the required plugins in the plugins directory according to the instructions below and matched the directory name with the php file name exactly.

> Before adding a new custom plugin, upload all of the plugin's files to a new folder in the following directory. If you want to update one of your custom plugins, refer to this directory likewise. Please note that the name of a plugin's folder must strictly match the name of the plugin, otherwise Pico will refuse to enable the plugin.

I tried Pico Pagination. I changed the directory name to 10-Pagination. But it is not enabled.

https://github.com/rewdy/Pico-Pagination

Many people are having trouble getting cms_pico to work on Nextcloud 26 or later. I have done a lot of research and tried everything, but it doesn't work.
Is there any plan to support 26 or 27 in the future?
If not, I will have to think of other alternatives.

Thank you in advance.

**Comment by PhrozenByte** [comment]
There's a known issue with the admin interface not listing prepared but not yet installed themes and plugins on Nextcloud 26 and later. I presume that this is the same issue, thus closing this as duplicate of #236. If it's indeed a different issue please let me know, I'll reopen this.

Considering compatibility with Nextcloud 26 and later: Pull requests on the [`cms_pico-1.0`](https://github.com/nextcloud/cms_pico/tree/cms_pico-1.0) branch to update the app are very welcome :+1:
