### ISSUE TITLE
Nextcloud 28.0.2 and PicoCms compatability 

### ISSUE THREAD

**Issue by ahm507** [nextcloud/cms_pico#245]
At the cms_pico page at [](https://apps.nextcloud.com/apps/cms_pico), last version supported is listed as 25, see:
![image](https://github.com/nextcloud/cms_pico/assets/6583178/5b72b0c9-1370-4970-972d-d2c624b4e312)

I did local installation to NextCloud Docker latest version "nextcloud:28.0.2-apache", when I try to install picoCMS, I see these: 
- The picoCms vestion stated is: 1.0.21
- "allow untested app" button appears
- "Server version 25 or lower is required" is shown.

How to make the cms_pico compatible?

**Comment by jkraffthha** [comment]
Checkout this issue: https://github.com/nextcloud/cms_pico/issues/237
