### ISSUE TITLE
Custom themes are lost when updating the app

### ISSUE THREAD

**Issue by azmeuk** [nextcloud/cms_pico#27]
The title is self-explanatory. I had a custom theme in `apps/cms_pico/Pico/themes` (that I have backuped), then it disappeared when I used the web updater to upgrade cms_pico to 0.9.6.
I could restore it, but it is pretty annoying if I need to do it at every new update. Also, the other admin users of my nextcloud installation do not know how to restore a theme, and may update the app

**Comment by daita** [comment]
Will be fixed next update
