### ISSUE TITLE
error messages 

### ISSUE THREAD

**Issue by NextGenerationcloud** [nextcloud/cms_pico#28]
copy(/var/webserv/meinecloud/apps/cms_pico/cms_pico/vendor/twig/twig/test/bootstrap.php):  failed to open stream: No such file or directory at  /var/webserv/meinecloud/lib/private/legacy/helper.php#191 | 2017-10-05T10:24:13+0200
-- | --
Error | PHP | copy(/var/webserv/meinecloud/apps/cms_pico/cms_pico/vendor/twig/twig/test/Twig/Tests/escapingTest.php):  failed to open stream: No such file or directory at  /var/webserv/meinecloud/lib/private/legacy/helper.php#191 | 2017-10-05T10:24:13+0200
Error | PHP | copy(/var/webserv/meinecloud/apps/cms_pico/cms_pico/vendor/twig/twig/test/Twig/Tests/Util/DeprecationCollectorTest.php):  failed to open stream: No such file or directory at  /var/webserv/meinecloud/lib/private/legacy/helper.php#191 | 2017-10-05T10:24:13+0200
Error | PHP | mkdir(): No such file or directory at /var/webserv/meinecloud/lib/private/legacy/helper.php#182 | 2017-10-05T10:24:13+0200
Error | PHP | copy(/var/webserv/meinecloud/apps/cms_pico/cms_pico/vendor/twig/twig/test/Twig/Tests/TokenStreamTest.php):  failed to open stream: No such file or directory at  /var/webserv/meinecloud/lib/private/legacy/helper.php#191 | 2017-10-05T10:24:13+0200
Error | PHP | copy(/var/webserv/meinecloud/apps/cms_pico/cms_pico/vendor/twig/twig/test/Twig/Tests/TemplateWrapperTest.php):  failed to open stream: No such file or directory at  /var/webserv/meinecloud/lib/private

Oo????

**Comment by daita** [comment]
What are you trying to achieve ?

**Comment by NextGenerationcloud** [comment]
only the update app ^^

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Can you please check whether your issue persists with Pico CMS for Nextcloud v1.0.0? I couldn't reproduce it. If your issue persists, please open a new Issue here on GitHub.
