### ISSUE TITLE
RFE: Restrict site by network

### ISSUE THREAD

**Issue by GregSutcliffe** [nextcloud/cms_pico#31]
This could be done in Apache config, I guess, but anyway ...

Some sites I have only make sense on the same network as the Nextcloud server (eg an internal wiki). I don't need it to be "private" (that is, anyone should be able to look a it), but only from, say, 192.168.1.0/24.

**Comment by daita** [comment]
This means a lot of work for a thing that can already done from Apache config :)

**Comment by GregSutcliffe** [comment]
Fair enough, worth asking ;)
