### ISSUE TITLE
App is not compliant according to "occ"

### ISSUE THREAD

**Issue by fmikker** [nextcloud/cms_pico#33]
I couldn't get Picocms plugin running on my site, so I started to investigate a bit, and found out that the "occ"-command does not think this app is compliant.

Is this a bug, or is it a user error when enabling the app?

Nextcloud info / cms_pico:

```php -v
PHP 7.0.10 (cli) (built: Nov  3 2016 08:06:03) ( NTS )```
```# sudo -u apache /opt/rh/rh-php70/root/bin/php /var/www/html/nextcloud/occ status
  - installed: true
  - version: 12.0.3.3
  - versionstring: 12.0.3
```

` - cms_pico: 0.9.6`

```# sudo -u apache /opt/rh/rh-php70/root/bin/php /var/www/html/nextcloud/occ app:check-code  cms_pico
Analysing /var/www/html/nextcloud/apps/cms_pico/lib/Pico.php
 1 errors
    line  134: OC_App - Static method of private class must not be called
App is not compliant
```

**Comment by daita** [comment]
Right now, can't find a way to do the same thing with a public class, so we'll keep it like this. Maybe with NC14.

**Comment by PhrozenByte** [comment]
Server currently doesn't provide the necessary API, I've created a appropriate PR, see nextcloud/server#16859

**Comment by fmikker** [comment]
Great work! I haven't tried to use cms_pico in a while, but now I'll have a look at it again :)
Happy holidays!

**Comment by PhrozenByte** [comment]
Thank you, the same to you!

However, I'll reopen this since it's still not really fixed (will be fixed as soon as we can raise the minimum requirement to Nextcloud 18). However, you can safely ignore the message.

**Comment by PhrozenByte** [comment]
The minimum requirement is now Nextcloud 18, thus this was finally fixed in https://github.com/nextcloud/cms_pico/commit/e040dc4df8db842aa39163011231edd3bdd3985e :+1:
