### ISSUE TITLE
Getting broken sites due to CSP

### ISSUE THREAD

**Issue by MG2R** [nextcloud/cms_pico#34]
I installed the Dimension theme featured on the Pico CMS website into a`pps/cms_pico/Pico/themes`, I enabled the theme and set the demo website found in the Dimension github repository as my website content.

When going to the index at `https://<mydomain>/index.php/apps/cms_pico/pico/<sitename>/index`, the site is quite broken because it can't load jQuery. I can see the following message in the console.

```
Refused to load the script 'https://<mydomain>/apps/cms_pico/Pico/themes/dimension/assets/js/jquery.min.js' because it violates the following Content Security Policy directive: "script-src 'nonce-<big-ass string>' 'unsafe-eval'".
```

How should I go about fixing this?

**Comment by dewomser** [comment]
I use the Pico default theme. Javascript modernizr does not load.  Despite a lot of Errors , Html and some css  load. The menue, links and pathes  are OK.
How should I go about fixing this?
+++
![screenshot_20171107_101103](https://user-images.githubusercontent.com/5160282/32485584-3eb3c1f0-c3a4-11e7-9692-d9558328cf15.png)

**Comment by Ludovicis** [comment]
same problem with travelify theme i can't use tinynav.min.js script and my navigation bar don't appear on mobile device.
Thanks for your help,

**Comment by Ludovicis** [comment]
I have find a solution with the help of xupefei from this issue: https://github.com/xupefei/Travelify/issues/3#issuecomment-351448561

you must follow this issue:
https://github.com/nextcloud/server/issues/2791

I have change my apache configuration with this line:
RewriteEngine on
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ https://www.%{HTTP_HOST}$1 [R=301,L]
Header always set Strict-Transport-Security "max-age=15768000;includeSubdomains;preload"
Header always set Content-Security-Policy "default-src 'self';frame-ancestors 'self';style-src 'self' 'unsafe-inline';script-src 'self' 'unsafe-inline' 'unsafe-eval';img-src 'self' data:;font-src 'self' data:"
Header always set X-Content-Type-Options "nosniff"
Header always set X-Frame-Options "sameorigin"
Header always set Referrer-Policy "strict-origin-when-cross-origin"
Header always set X-XSS-Protection "1; mode=block"
<Directory />
    #Options FollowSymLinks
    #AllowOverride All
    Header unset "X-Content-Type-Options"
    Header unset "X-Frame-Options"
    Header unset "X-XSS-Protection"
    Header unset "Public-Key-Pins"
    Header unset "Content-Security-Policy"
    Header unset "Strict-Transport-Security"
    Header unset "Referrer-Policy"
</Directory>

And after restart apache service no more csp error and js script work

**Comment by MG2R** [comment]
I feel that this should be stuff done by the cms_pico module. Seems more like a hack than an actual solution.

**Comment by Ludovicis** [comment]
i think the same is a hack

**Comment by dewomser** [comment]
I see Problem in the http-header.  Nextcloud does not allow to execute some  css and js . It's the wrong way to allow this for nextcloud  in an Apache-patch. Only cms_pico should be allowed.   Shows http-header in the shell : curl -I your_pico_url

**Comment by dewomser** [comment]
Workaround:
I just added one line to apache - virtualhost - configuration.
**Header unset "Content-Security-Policy"**
And still get A+ ranking  at https://scan.nextcloud.com/

**Comment by Ludovicis** [comment]
Me also with the apache config designated above A+

**Comment by poVoq** [comment]
Is there a way this could work on a shared host with only .htaccess modification?

**Comment by realitygaps** [comment]
@poVoq you should be able to use:
`Header unset "Content-Security-Policy" `
in .htaccess files also

**Comment by fbclol** [comment]
I have may be little solution !

put/edite file ./lib/Pico.php  : 
 ```
protected function getTwigVariables() {
                $twigVariables = parent::getTwigVariables();
                $twigVariables['theme_url'] = \OC_App::getAppWebPath(Application::APP_NAME) . '/Pico/themes/' . $this->getConfig('theme');
                $twigVariables['nonce']     = \OC::$server->getContentSecurityPolicyNonceManager()->getNonce(); 
                return $twigVariables;
        }

```
New row :
`  $twigVariables['nonce']     = \OC::$server->getContentSecurityPolicyNonceManager()->getNonce(); `

And edit file *.twig (Example) : 
<script nonce="{{ nonce }}" src="{{ theme_url }}/js/masonry.pkgd.min.js"></script>


eidt file ./appinfo/app.php (example) : 
add row before  require_once .....

```
if(class_exists('\\OCP\\AppFramework\\Http\\EmptyContentSecurityPolicy')) {
	$manager = \OC::$server->getContentSecurityPolicyManager();
	$policy = new \OCP\AppFramework\Http\EmptyContentSecurityPolicy();
	$policy->addAllowedStyleDomain('\'self\'');
    $policy->addAllowedStyleDomain('\'unsafe-inline\'');
    $policy->addAllowedStyleDomain('https://fonts.googleapis.com');
    $policy->addAllowedScriptDomain('\'self\'');
    $policy->addAllowedStyleDomain('https://fonts.googleapis.com');
    $policy->addAllowedScriptDomain('\'unsafe-inline\'');
    $policy->addAllowedScriptDomain('ajax.googleapis.com');
	$policy->addAllowedImageDomain('\'self\'');
	$policy->addAllowedImageDomain('data:');
	$policy->addAllowedImageDomain('blob:');
	$policy->addAllowedMediaDomain('\'self\'');
    $policy->addAllowedMediaDomain('blob:');
    $policy->addAllowedFontDomain('fonts.gstatic.com');
	$policy->addAllowedChildSrcDomain('\'self\'');
	$policy->addAllowedConnectDomain('\'self\'');
	$boshUrl = \OC::$server->getConfig()->getAppValue('cms_pico', 'boshUrl');
	if(preg_match('#^(https?:)?//([a-z0-9][a-z0-9\-.]*[a-z0-9](:[0-9]+)?)/#i', $boshUrl, $matches)) {
		$boshDomain = $matches[2];
		$policy->addAllowedConnectDomain($boshDomain);
	}
	$externalServices = \OC::$server->getConfig()->getAppValue('cms_pico', 'externalServices');
	$externalServices = explode("|", $externalServices);
	foreach($externalServices as $es) {
		$policy->addAllowedConnectDomain($es);
	}
	$manager->addDefaultPolicy($policy);
}
```

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Pico CMS for Nextcloud v1.0.0 uses its own, less restrictive CSP. However, it still isn't as loose as having no CSP at all due to security considerations, thus some themes might still be broken. Can you please check whether your issue persists with Pico CMS for Nextcloud v1.0.0? If it does, please open a new issue on GitHub.
