### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by thesteff** [nextcloud/cms_pico#36]
Hi !

How can I can include audio files (and the associated audio player) to a pico page using the markdown syntax ?

Now, I generate a public link with my files and use it in my markdown page but the user is obliged to access the download page with this link, download the file and read it with a local player. It could be far more simpler to read an audio file directly with the brower's player but I don't find how to do it (markdown syntax or/and nextcloud access).

Thanks!

**Comment by sunjam** [comment]
[Have you tried embedding audio files as is recommended here?](https://github.com/getpelican/pelican/issues/1099)

**Comment by daita** [comment]
Please reopen this ticket if @sunjam answer is not enough.

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Reopening this to check whether we might add `<audio>` and `<video>` to HTMLPurifier's element whitelist.

**Comment by PhrozenByte** [comment]
Fixed in Pico CMS for Nextcloud v1.0.0
