### ISSUE TITLE
Apache configuration difficulty

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/cms_pico#39]
hello to all

I'm having a difficulty to understand the configuration of apache to cms pico to work.

In https://github.com/nextcloud/cms_pico/wiki/Admin-Settings#customizing, it is indicated what should be copied to the configuration of Apache, but it does not say how to do it.

What is the config file in cause?
 is /etc/apache2/apache2.config or something else. 
I'm skeptical to touch in these files because it may damage may nextcloud instance

**Comment by daita** [comment]
Try to find someone with administration knowledge and your OS/distribution on help.nextcloud.com

**Comment by TheNomad11** [comment]
Nextcloud announced it as an easy website builder but it seems it is only made for geeks. Can somebody give understándable instructions how to configure apache correctly? People on help.nextcloud.com are struggling as well and giving up Pico for this reason
