### ISSUE TITLE
Possibly wrong themePath displayed

### ISSUE THREAD

**Issue by scholer** [nextcloud/cms_pico#45]
Commit `2a6113b7` updated `templates/settings.admin.php`, displaying the actual directory where the user should place new themes, rather than just saying `'apps/cms_pico/Pico/themes/'`. Displaying the directory where themes should be placed is done with `$_['pathToThemes']`.

This is a good change and potentially very helpful to the user. However, in my case `$_['pathToThemes']` displays as `/var/ncdata/appdata_ocmnpoor4wsx/cms_pico/themes/`, i.e. the APPDATA directory, not the INSTALL directory. Themes in the `$APPDATA/cms_pico/themes` directory are indeed detected by the admin panel JS, but, at least to me, they don't work when "installed" through the admin panel. I need them to be in the install directory, which in my case is `/var/www/nextcloud/apps/cms_pico/Pico/themes/`, before the themes work. Otherwise the various css and js files aren't found.

I assume one of the following is the issue:

1. There is something wrong with my nextcloud/pico setup, or 
2. The wrong directory is displayed with `$_['pathToThemes']` (i.e. it should show the install directory, not the appdata directory), or
3. The installation of the themes in APPDATA goes wrong and the themes are not properly installed.
4. There is a bug somewhere which means that themes in $APPDATA/cms_pico/themes aren't found, only the files in $INSTALL/apps/cms_pico/Pico/themes.

I have manually resolved my issue by making symlinks in `/var/www/nextcloud/apps/cms_pico/Pico/themes/` (the INSTALL directory) which points to the themes in `/var/ncdata/appdata_ocmnpoor4wsx/cms_pico/themes/` (the APPDATA directory).

**Comment by avanc** [comment]
I also struggled over the theme path.
First, I installed a theme into `$INSTALLDIR/apps/cms_pico/Pico/themes`. However, the admin backend could find the directory, so I couldn't activate it.

Thus, I moved it to $APPDATA/cms_pico/themes. Thereafter, I could select the theme in the admin backend. The TWIG templates are also found while rendering the page. However, external files (CSS and fonts) cannot be found (404) althoug they are available in the same directory.

I'm wondering what it special about the default theme, as in renders at expected.

**Comment by avanc** [comment]
As an intermediate solution, I copied my theme folder to both locations, and it works. But I guess this is not intended.

**Comment by PhieF** [comment]
Hi, still not working, themes on my side have to be in 
/var/www/html/nextcloud/apps/cms_pico/themes

and not in the data folder

**Comment by geotheory** [comment]
I've tried copying my `/var/ncdata/appdata_.../cms_pico/themes` folder contents to `/var/www/html/nextcloud/apps/cms_pico/themes` (my correct path) and get the same failures for respective themes as before.

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

The handling of custom themes in `cms_pico` v0.9.8 unfortunately was kinda broken. Please try Pico CMS for Nextcloud v1.0.0 to check whether your problem persists. If it does, please open a new Issue here on GitHub.
