### ISSUE TITLE
PHP Fatal error:  Class 'Pico' not found in /var/www/nextcloud/apps/cms_pico/lib/Pico.php on line 32

### ISSUE THREAD

**Issue by 4001982248998** [nextcloud/cms_pico#46]
After app installation,  ``composer install`` and  extending the apache configuration, Pico sites only display a blank, white page.

The apache error log mentions this single line:
``
PHP Fatal error:  Class 'Pico' not found in /var/www/nextcloud/apps/cms_pico/lib/Pico.php on line 32
``

**Comment by dieterkoenig** [comment]
@4001982248998 I ran into exactly the same problem - have you been able to resolve it? thanks in advance

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Can you please check whether your issue persists with Pico CMS for Nextcloud v1.0.0? I couldn't reproduce it. If your issue persists, please open a new Issue here on GitHub.
