### ISSUE TITLE
Invalid twig template leads to full path disclosure

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/cms_pico#5]
When adding `{% include '/etc/passwd' %}` to a Twig template the following error message is displayed to the user:

"Unable to find template \"\/etc\/passwd\" (looked into: \/tmp\/asdsadsads\/admin\/files\/my_site1\/themes\/default) in \"index.twig\" at line 5."

**Comment by LukasReschke** [comment]
We should probably catch any exception and show a generic error page instead of the exact error message :)

**Comment by daita** [comment]
Was thinking about this. The safer is to replace all exception, or string replace the absolutepath of the cloud from the exception message.

Thought ?
