### ISSUE TITLE
Apache Configuration is not Well Documented

### ISSUE THREAD

**Issue by CodyWarmbo** [nextcloud/cms_pico#51]
"Copy one of the example below and paste the line in your Apache configuration " is the line in the Pico CMS settings area, but it does not specify where to paste this line. When I attempted to do so Apache would not start any longer and I had to revert the change.

A clearer example should be given.

**Comment by diplodata** [comment]
Agreed. This is my `/etc/apache2/sites-available` folder. It's guesswork.

```
-rw-r--r-- 1 root root 1327 Apr  6 08:21 000-default.conf
-rw-r--r-- 1 root root 6479 Apr 14 23:24 default-ssl.conf
-rw-r--r-- 1 root root  617 Apr  6 08:04 nextcloud_http_domain_self_signed.conf
-rw-r--r-- 1 root root  871 Apr 14 23:23 nextcloud_ssl_domain_self_signed.conf
-rw-r--r-- 1 root root 1749 Apr 11 14:06 sosc.cloud.conf
-rw-r--r-- 1 root root  840 Apr 10 09:16 sosc.cloud.conf.new
-rw-r--r-- 1 root root 1749 Apr 10 06:47 sosc.cloud.conf.orig
-rw-r--r-- 1 root root  195 Apr 10 07:32 sosc-redir.conf
```

**Comment by GustavoMarcante** [comment]
I also included this points, that were blocking the use of Pico CMS to me:
https://github.com/nextcloud/cms_pico/pull/60
https://github.com/nextcloud/cms_pico/issues/61
Thanks for the nice work!

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

We improved the in-app webserver configuration instructions, I hope those are a bit clearer. Additionally you won't need to configure your webserver to get Pico CMS for Nextcloud running, it's now an optional feature. You can check out v1.0.0 to test whether it resolves your issue. If not, please open a new Issue here on GitHub.
