### ISSUE TITLE
When i make a copy of the default template to my own all the css/javascript is not accepted, why?

### ISSUE THREAD

**Issue by kdeenkhoorn** [nextcloud/cms_pico#53]
Dear all,

I want to make my own template copied from the default template.
When i copy the 'default' template directory to my own version say 'MyOwn' i can select this new template in NextCloud. But when i assign it to a site all external files in the template will not be rendered.
No css files, no javascript files etc.
In the codeviewer of the webbrowser i can see the URL's to the files but when i access them i get the loginscreen of Nextcloud.

Why ??

I'm running nextcloud 13.

Thanks in advance,

Klaas Eenkhoorn.

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

The handling of custom themes in `cms_pico` v0.9.8 unfortunately was kinda broken. Please try Pico CMS for Nextcloud v1.0.0 to check whether your problem persists. If it does, please open a new Issue here on GitHub.
