### ISSUE TITLE
picocms's Twig content filter extension

### ISSUE THREAD

**Issue by anernest** [nextcloud/cms_pico#54]
I've been trying to use the content filter that is registered as a simple twig extension in pico with no luck. Trying to include content from other pages (e.g. below) in a template produces nothing. 

```
{% for page in pages %}
	{{ page.id|content }}<br/><br/>
{% endfor %}
```

I haven't tried it with a standalone instance of pico, but it appears to be a working filter according to other posts (https://github.com/picocms/Pico/issues/403) on the picocms github repo.

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Can you please check whether your issue persists with Pico CMS for Nextcloud v1.0.0? I couldn't reproduce it. If your issue persists, please open a new Issue here on GitHub.
