### ISSUE TITLE
Picocms pages does not work on iPad

### ISSUE THREAD

**Issue by rollanders** [nextcloud/cms_pico#62]
The default theme does not work on iPad. I only see part of the pages. Cannot scroll the page. Same result with Safari or Chrome browser on the ipad.

**Comment by rollanders** [comment]
After reinstalling Pico using these instructions https://www.c-rieger.de/nextcloud-meets-picocms/ I had no problem. These installation uses the latest version of PICO which may have done the difference

**Comment by dcrobertson01** [comment]
page seems to be missing
