### ISSUE TITLE
How to install plugins

### ISSUE THREAD

**Issue by Spica2** [nextcloud/cms_pico#63]
I would like to use PicoOutput plugin, but the normal install routine is not the same.

How to activate in the config:
PicoOutput:
    formats: [content, raw, prepared, json, xml]

**Comment by koug44** [comment]
Same thing here with the «Pico Users» plugin for access managment

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

Pico CMS for Nextcloud v1.0.0 explicitly supports adding custom plugins (`cms_pico` v0.9.8 supported this, too, even though it wasn't documented). You can find Pico's `config.yml` in the `data/appdata_*/cms_pico/config` directory.

If you have any more issues, please open a new Issue here on GitHub.
