### ISSUE TITLE
Upgrade to Pico 2

### ISSUE THREAD

**Issue by nsrosenqvist** [nextcloud/cms_pico#64]
Are there any plans on upgrading to Pico 2? I'm not familiar with how the app uses Pico, would it be possible to just bump the version in composer.json or is it much more complicated than that?

**Comment by nsrosenqvist** [comment]
@daita?

**Comment by rollanders** [comment]
I have used these instructions and it installed Pico 2. 
https://www.c-rieger.de/nextcloud-meets-picocms/
How to upgrade?

**Comment by PhrozenByte** [comment]
Done :laughing:

Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.
