### ISSUE TITLE
Themes do not render properly

### ISSUE THREAD

**Issue by irregularisnotrandom** [nextcloud/cms_pico#65]
Hi

I installed some themes as described in the doc. I can see the themes and assign them in the settings but they are nothing like it is shown in the Pico web site.

Here are couple 

https://github.com/blocknotes/just-pico

https://github.com/smcdougall/NotePaper

thanks

**Comment by irregularisnotrandom** [comment]
Also the default theme from Pico is actually responsive to mobile while the same default theme in cms-pico is not.

thanks

**Comment by FadeFx** [comment]
Same problem here, seems like on the forum one user reported that themes work for him, but not how he solved the issue. 
https://help.nextcloud.com/t/applying-a-pico-cms-theme-any-theme/30791/7

However, i installed cms_pico after that post in nextcloud 14.x and could not get just-pico to work.

**Comment by FadeFx** [comment]
I think this is related to #34

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

The handling of custom themes in `cms_pico` v0.9.8 unfortunately was kinda broken. Please try Pico CMS for Nextcloud v1.0.0 to check whether your problem persists. If it does, please open a new Issue here on GitHub.
