### ISSUE TITLE
Themes not loading files

### ISSUE THREAD

**Issue by dcrobertson01** [nextcloud/cms_pico#66]
Hi - I have had a look at a lot of posts here but don’t see where people have resolved this. Are there still issues with the pico_cms plugin? I posted on the Nextcloud community site but got no reply. Is the project still going?

My issues are:

I have installed the module, and have set up a site. The default theme is working perfectly. I would like to use my own theme though.

I have uploaded my theme to the nextcloud data/appdata directory, I can add it as administrator and as a user, I can apply it to my site.

This is where it gets tricky. I do not seem to be able to add any additional css files or javascript files. In my theme template.twig I have

```
<link rel='stylesheet' href="{{ theme_url }}/styles/style.css" type='text/css'/>
<link rel="stylesheet" href="{{ theme_url }}/style.css" type="text/css" />
```
These links get rendered as

```
<link rel="stylesheet" href="/apps/cms_pico/Pico/themes/default/styles/style.css" type='text/css'/>
<link rel="stylesheet" href="/apps/cms_pico/Pico/themes/default/style.css" type="text/css" />
```
The second stylesheet will load, but the first one will not. The first one will be redirected to the Nextcloud files app. The second one is copied from the default template. As far as I can see, the permissions are okay on all the folders and files.

Adding  a new css file to the default template fails also. 

Weirder are the scripts. In my twig template, I have

```
<script src="{{ theme_url }}/scripts/unslider-min.js"></script>
<script src="{{ theme_url }}/scripts/modernizr-2.6.1.min.js"></script>
```
which renders as

```
<script src="/apps/cms_pico/Pico/themes/default/scripts/unslider-min.js"></script>
<script src="/apps/cms_pico/Pico/themes/default/scripts/modernizr-2.6.1.min.js"></script>
```
The second has been copied from the default template, and the file moved into my theme. The first is not loaded, the second is.

Is there some setting somewhere that says which files can be added to the templates? I’ve been trying to find out what is going on, and am confused.

Any hints would be appreciated. Cheers

Don

**Comment by steinQF** [comment]
Bump: I'm having the same problem and would appreciate a clean solution.

**Comment by steinQF** [comment]
A possible workaround is to add theme files not just to the nextcloud data folder but also to the repsective nextcloud web folder. That solved the issue for me.

**Comment by dcrobertson01** [comment]
Hi - was pretty sure I had posted more on this but maybe not. Can't find it anyway.

What I did was to add a system link to link nextcloud/apps/cms_pico/themes to nextcloud_data/appdata/ cms_pico/themes 

The system link means you don't have to remember which files go in which theme directory.

I have had a go at updating to the latest pico release but with no luck.

**Comment by dcrobertson01** [comment]
Here is a discussion on the Nextcloud site.

https://help.nextcloud.com/t/themes-for-pico/44522

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

The handling of custom themes in `cms_pico` v0.9.8 unfortunately was kinda broken. Please try Pico CMS for Nextcloud v1.0.0 to check whether your problem persists. If it does, please open a new Issue here on GitHub.
