### ISSUE TITLE
URL file size

### ISSUE THREAD

**Issue by zhangdashuo** [nextcloud/cms_pico#69]
When the file size is larger than several hundred megabytes, the URL can not be referenced externally. The tens of megabytes of files I tested can be used. I would like to ask, is there a limit on the size of the URL file in the code?

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

What do you mean by "URL file size"? Uploading files using a form? Downloading files with several hundred megabytes shouldn't be any problem with Nextcloud...
