### ISSUE TITLE
Incompatible with Nextcloud 15

### ISSUE THREAD

**Issue by Windyo** [nextcloud/cms_pico#70]
Plugin needs updating to be compatible with Nextcloud 15.

**Comment by raneon** [comment]
I've upgraded as well to Nextcloud 15 and now Pico CMS is not working anymore. It would be nice if it could get an update :-)

**Comment by Windyo** [comment]
Actually have a pull request to fix this it's literally just the info.XML to change. Check PR71

You can even do that on your server directly without downloading jack shit.

**Comment by andyboeh** [comment]
It would be great to have that fixed officially since otherwise upgrading the cloud instance is more difficult.

**Comment by madmax911** [comment]
I've installed it via changing the info.xml file and it seems to work but am unable to show sites - 404.  I looked at the in-app docs and it states changes to make to the apache file but I'm using lighttpd.  I located some docs for configuring lighttpd.  It references some file config/config.yml but I have no idea where to find this.  Any suggestions?

**Comment by blvb** [comment]
Edited info.xml. Looks good in Nextcloud apps list, but Use shows "Webpage cannot be rendered"

**Comment by azmeuk** [comment]
There has not been any real commit since more than a year. Is this app even being supported still?

**Comment by Windyo** [comment]
I mean if we're being honest the ideal way of handling this would be to write an app to load the standard cms_pico PHP files instead of the really custom thing here.

Esp as this is still pico1

Anon

________________________________
