### ISSUE TITLE
[solved] site only available public, not private

### ISSUE THREAD

**Issue by tre-bor** [nextcloud/cms_pico#75]
**Nextcloud Version**
16.0.1
**What I did**
- created a new site using pico-cms in nextcloud
- set status to "private"

**expected behaviour**
I would have access the site, when I'm logged in to nextcloud.

**behaviour indeed**

> Website is private. You do not have access to this website.

By the way, accessing the site when set public is no problem.

**Comment by tre-bor** [comment]
It worked when I tried to access the page outside the local network. The issue may be related to DNS-Rebind?

**Comment by PhrozenByte** [comment]
Pico CMS for Nextcloud v1.0.0 is arriving and I'm currently working through some old issues that can be resolved before releasing the app's first stable release. See [help.nextcloud.com](https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718) for more info.

I assume you solved your issue. You can check out v1.0.0 now to see whether your problem persists or not. If it does, please open a new Issue here on GitHub.
