### ISSUE TITLE
Incompatible with Nextcloud 17 (beta 2)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/cms_pico#79]
I upgraded NC successfully except for Pico CMS. What is needed to integrate with NC 17?
Currently, "activating untested app" shows neither admin nor user Pico CMS menu entries nor are sites displayed, so our blog is offline now ;)

**Comment by nursoda** [comment]
Sorry, I was SO blind, it was not activated yet. Nevertheless, it should be made fully compatible to NC 17 ;-)

**Comment by PhrozenByte** [comment]
You might want to test the current beta of Pico CMS for Nextcloud v1.0.0 which is fully compatible with Nextcloud 17, see https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718 for more info.

**Comment by nursoda** [comment]
OK, but not now (currently on holiday), probably end of next week. With 0.9.8 we had CSP issues in NC17 that we solved temporarily by disabling CSP for the cms_pico location.
