### ISSUE TITLE
After deleting the blog, the icon remains in the menu bar

### ISSUE THREAD

**Issue by poltrian** [nextcloud/cms_pico#82]
Hello,
I tried Pico for Nextcloud. I have deleted the created blog but the globe icon still remains in the Nextcloud menu bar.

Then I deactivate Pico, then I have the menu bar twice when I click on the Globis icon.

Also uninstall and reinstall does not help. How can I delete the icon?

Thanks

Regards

Olaf

**Comment by PhrozenByte** [comment]
I honestly just don't understand what you were doing, what you were trying to do, what the actual issue is or what icons/menus you referring to. Please elaborate further, e.g. with screenshots.

**Comment by poltrian** [comment]
Hello,
thats what i mean:



No CMS Page 

But the Icon ist still present
after deactivating Pico Tool bar is twice

And the deleted Webpage "Der Blog" is also shown. 
How can i remove the icon?
Thnaks
Regards
Olaf 




Am Mittwoch, den 02.10.2019, 05:49 -0700 schrieb Daniel Rudolf:

**Comment by poltrian** [comment]
> I honestly just don't understand what you were doing, what you were trying to do, what the actual issue is or what icons/menus you referring to. Please elaborate further, e.g. with screenshots.

i m sorry can bei closed its my fault. I use external sites und there was the Pico link included. Sorry again
