### ISSUE TITLE
Improve installation documentation 

### ISSUE THREAD

**Issue by arthurlogilab** [nextcloud/cms_pico#84]
After installing the application via the admin interface, I can create a "site" which creates a folder with prefilled content, that's great. 

I don't know where to type `composer install` on my system. 

on top of that composer isn't installed as global tool on my system : 

```
root@y:~# composer
-bash: composer: command not found
```

Thanks for clearing things up.

**Comment by PhrozenByte** [comment]
Just download one of the pre-build release packages (`cms_pico-*.tar.gz`): https://github.com/nextcloud/cms_pico/releases

**Comment by arthurlogilab** [comment]
@PhrozenByte thanks for taking the time to respond. But where do I put / extract this release ?

**Comment by arthurlogilab** [comment]
Maybe there is some confusion, the files in the release are already present on my server in `/var/www/nextcloud/apps/cms_pico` which is deployed when I click "install" in the nextcloud admin interface.

**Comment by PhrozenByte** [comment]
Then you don't have to do anything. The install instructions only apply for manual installations. Starting with v1.0.0 (currently in beta, you might want to give it a try) there will be more precise instructions in the `README.md`, see #77 and https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718
