### ISSUE TITLE
Update for Nextcloud 17.0.0

### ISSUE THREAD

**Issue by Vrakfall** [nextcloud/cms_pico#86]
Hello,
I've just noticed that this app isn't updated for Nextcloud's last version, `17.0.0`. This app seems great and I would really like to give it a try but the fact it doesn't work for the last version keeps me from doing so. :/

Thank you in advance!

**Comment by PhrozenByte** [comment]
You can safely enable the old v0.9 for Nextcloud 17 using the button in Nextcloud's web interface. However, I rather suggest using the latest beta of Pico CMS for Nextcloud v1.0, also see #77 and https://help.nextcloud.com/t/beta-needs-testing-pico-cms-for-nextcloud-v1-0-0/58718. Beta 2 (will be released in the next couple of days) will be in the app store, too.

**Comment by Vrakfall** [comment]
Interesting, thank you!
Even for production? In your link you said one shouldn't use the beta for production usage.

**Comment by PhrozenByte** [comment]
I'd expect more issues with the old v0.9 than with the beta of v1.0 :smile: The purpose of a beta is to test stability and we didn't have any issues. Just keep in mind to check the provided help.nextcloud.com thread before upgrading the beta to a newer version.

**Comment by Vrakfall** [comment]
Thank you.
I'm more worried about security than stability. I'll surely check the beta out.
