### ISSUE TITLE
V1.0.0 i can't activate app Cannot declare class PicoDeprecated, because the name is already in use at ...

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/cms_pico#89]
Hello,
Thanks for this update, I had this error, i can't activate cms_pico app. 
\/settings\/apps\/enable","message":"Cannot declare class PicoDeprecated, because the name is already in use at \/var\/www\/html\/nextcloud\/apps\/cms_pico\/appdata_public\/plugins\/wFpuVwcG88\/PicoDeprecated\/PicoDeprecated.php#383"

Thanks for your help

**Comment by PhrozenByte** [comment]
Which custom plugins did you use before upgrading to Pico CMS for Nextcloud v1.0.0? You must remove any previously existing instance of `PicoDeprecated` before upgrading, because starting with v1.0.0 `PicoDeprecated` is shipped together with Pico CMS for Nextcloud.

**Comment by andyboeh** [comment]
I had the exact same problem. What helped was the following:

  - Uninstall the app
  - Go the the Nextcloud database, I used "phpMyAdmin"
  - Navigate to the table oc_appconfig
  - Delete all entries for appid "cms_pico"
  - Install the plugin

**Comment by Ludovicis** [comment]
Thanks andyboeh,
your solution worked.

**Comment by PhrozenByte** [comment]
Just for record: This issue has been fixed now. It will cause no issues starting with Pico CMS for Nextcloud v1.0.1 (will be released this weekend). In the meantime it's very easy to circumvent this issue. See https://help.nextcloud.com/t/pico-cms-for-nextcloud-v1-0-0-is-out-now/64975/7 for more info.
