### ISSUE TITLE
Requesting a nonexistent page returns the 404.md file but a 200 status code 

### ISSUE THREAD

**Issue by doftnet** [nextcloud/cms_pico#90]
One thing that bothered me with the older cms_pico was that if I requested a nonexistent page, while it would return my 404.md content, in the underlying response headers, it was still a 200 OK.

Poking around in the code, I found a line in vendor/picocms/lib/Pico.php that attempts to set the response to 404 in the event that the 404 page needs to be loaded, but that never manages to make it out to the final response.  While this is something that a typical site visitor probably wouldn't care too much about, I think it's important to return accurate responses for indexing and logging purposes.

**Comment by doftnet** [comment]
with a couple of simple changes, I was able to pass the 404 status back out so that the correct status is reported to the browser and the server logs.  I can submit a pull request with the changes in a bit, if you'd like to look it over - I'm not sure it's the best way to handle it but it works.

**Comment by PhrozenByte** [comment]
Sure, looking forward to it, thank you! :+1:
