### ISSUE TITLE
Congrats on Pico for Nextcloud! Can Pico content be synced to a Git/GitHub repo?

### ISSUE THREAD

**Issue by paulhibbitts** [nextcloud/cms_pico#94]
Hello!

Great to see Pico on Nextcloud now! Not sure if this is the best place to ask, but is it possible (or any plans) to store or sync Pico MD files hosted on Nextcloud to a Git/GitHub repo?

Thanks very much,
Paul

**Comment by PhrozenByte** [comment]
I don't think that this is possible, because there's AFAIK no Git implementation in PHP. However, if you want to use a Git repo, I'd suggest using pure [Pico](http://picocms.org), since Git kinda takes care of the "file sharing" part anyway.

**Comment by paulhibbitts** [comment]
Thanks for the info @PhrozenByte , I appreciate your quick reply.
