### ISSUE TITLE
Installation  for 1.0.2 fails with message: App "cms_pico" cannot be installed because appinfo file cannot be read"

### ISSUE THREAD

**Issue by rkilchmn** [nextcloud/cms_pico#96]
Installation from App Store of 1.0.2 fails on NC 17.0.1

<img width="731" alt="Installation pico_cms_1 0 2 fails" src="https://user-images.githubusercontent.com/33502448/70239553-c9a20700-176b-11ea-8fb7-ee8d552a5cbc.PNG">

**Comment by rkilchmn** [comment]
Tried again with delete app dir

**Comment by w1n5l0w** [comment]
Gettin the same error NC 17.0.2 Pico 1.0.4. Deleting app dir and trying to reinstall doesn't help.
