### ISSUE TITLE
Rendering of markdown syntax page looses anchor for in page navigation

### ISSUE THREAD

**Issue by mau2806** [nextcloud/cms_pico#98]
I transferred the markdown syntax docu page:
https://daringfireball.net/projects/markdown/syntax.text
to an nextcloud cms_pico document. Calling the page via my nextcloud from a web browser the page is rendered as expected, but the Headlines at the beginning showing links to the paragraphs below (e.g. "Headers") don't let me change to the corresponding paragraph. Inspecting the generated html code shows the difference:

html code generated on https://daringfireball.net/projects/markdown/syntax
<h3 id="header">Headers</h3>

html code generated out of nextcloud cms_pico
<h3>Headers</h3>

the id tag is missing.

**Comment by PhrozenByte** [comment]
HTMLPurifier removes HTML element IDs by default, see http://htmlpurifier.org/docs/enduser-id.html. Since it's very unlikely that this causes a XSS issue, we will change HTMLPurifier's default behaviour with the next release.
